### ISSUE TITLE
RPi4

### ISSUE THREAD

**Issue by summitbri** [roflcoopter/viseron#1]
Thought I'd try to fire up this docker on a Pi4.  All of the initialization works fine, then getting the errors below with ffmpeg.  Any thoughts?

ffmpeg -hide_banner -loglevel panic -avoid_negative_ts make_zero -fflags nobuffer -flags low_delay -strict experimental -fflags +genpts -stimeout 5000000 -use_wallclock_as_timestamps 1 -vsync 0 -c:v h264_mmal -rtsp_transport tcp -i rtsp://admin:PWXXXX@192.168.1.160:554/Stream/Channels/102/ -f rawvideo -pix_fmt nv12 pipe:1

mmal: mmal_vc_port_info_set: failed to set port info (2:0): EINVAL
mmal: mmal_vc_port_set_format: mmal_vc_port_info_set failed 0x8e4bf0 (EINVAL)
mmal: mmal_port_disable: port vc.ril.video_decode:in:0(H264)(0x8e4bf0) is not enabled
mmal: mmal_port_disable: port vc.ril.video_decode:out:0(0x8e2f00) is not enabled
mmal: mmal_port_disable: port vc.ril.video_decode:ctr:0(0x8e48e0) is not enabled

**Comment by roflcoopter** [comment]
Thanks for showing interest in the project!
I think you need to increase the gpu_mem in /boot/config.txt.

I just added some information about this to the README.
Check the RaspberryPi 3b+ section under Getting Started

**Comment by summitbri** [comment]
Increasing the gpu_mem as far up as 512 didn't work, but I tried the ffmpeg command build for VAAPI support and it didn't error out.
ffmpeg -hide_banner -loglevel panic -avoid_negative_ts make_zero -fflags nobuffer -flags low_delay -strict experimental -fflags +genpts -stimeout 5000000 -use_wallclock_as_timestamps 1 -vsync 0 -hwaccel vaapi -vaapi_device /dev/dri/renderD128 -rtsp_transport tcp -i rtsp://admin:PWXXXX@192.168.1.160:554/Stream/Channels/102/ -f rawvideo -pix_fmt nv12 pipe:1

**Comment by roflcoopter** [comment]
Interesting! I don't have an RPI4 to test with sadly. How's the CPU usage?

I'll look into it more and see if I can figure out what's going on.

**Comment by roflcoopter** [comment]
Btw, could you post your docker run command?

**Comment by summitbri** [comment]
CPU usage is under 10%.  Docker run and config files are below.  I have a Coral TPU attached.  Also I'm able to display the rtsp stream with ffplay just fine.

docker run --rm \
--privileged \
-v /home/pi/nvr/recordings:/recordings \
-v /home/pi/nvr/config:/config \
-v /etc/localtime:/etc/localtime:ro \
-v /dev/bus/usb:/dev/bus/usb --privileged \
-v /opt/vc/lib:/opt/vc/lib \
--name viseron \
--device /dev/vchiq:/dev/vchiq --device /dev/vcsm:/dev/vcsm --device /dev/dri \
roflcoopter/viseron-rpi:latest

# See the README for the full list of configuration options.
cameras:
  - name: doorbell
    host: 192.168.1.160
    port: 554
    username: admin
    password: <redacted>
    path: /Stream/Channels/101/
    width: 2048
    height: 1536
    fps: 5 
    motion_detection:
      interval: 1
      trigger: false
    object_detection:
      interval: 1
      labels:
        - label: person
          confidence: 0.9
        - label: pottedplant
          confidence: 0.9

# MQTT is optional
#mqtt:
#  broker: localhost
#  port: 1883
#  username: <if auth is enabled>
#  password: <if auth is enabled>

**Comment by summitbri** [comment]
btw, I just looked at ffmpeg -hwaccels and here is the list available.  I've tried to recompile ffmpeg a few times and haven't been able to get MMAL to show up on the list.  

Hardware acceleration methods:
vdpau
vaapi
drm
rpi
rpi

**Comment by roflcoopter** [comment]
Can you try to take a look at [this guide](https://jellyfin.org/docs/general/administration/hardware-acceleration.html#raspberry-pi-3-and-4) from jellyfin? From what i have been able to gather, the h264_mmal decoding should work on the RPi4, however H264_omx encoding might not.

**Comment by summitbri** [comment]
Thanks for that, I actually looked at that guide previously.  I did find this that might offer some other clues.  https://raspberrypi.stackexchange.com/questions/108613/rpi-4-ffmpeg-how-to-get-hardware-h-264-decoding-to-work

We probably need someone smarter than me to figure out the RPi4 implementation.

**Comment by roflcoopter** [comment]
I am sorry i cant be of much help here, hard for me to assist without the hardware.
I plan on eventually getting an RPi4 and troubleshoot, but that could be a while.

**Comment by rickalm** [comment]
I'm interested in sorting this out, where can I find the Dockerfile for the rpi3 build ?

**Comment by roflcoopter** [comment]
Great! The dockerfiles for RPi are placed [here](https://github.com/roflcoopter/viseron/tree/master/docker/rpi)

**Comment by roflcoopter** [comment]
@summitbri @rickalm I dont know if you are still intersted in this, but the latest beta, 1.8.0b5, has experimental support for the RPi4.

I need someone to test it out for me tho and squash the last bugs. Could any of you take a look?

**Comment by summitbri** [comment]
@roflcoopter unfortunately I don't have an available RPI4 to test this on right now.  Sorry!

**Comment by roflcoopter** [comment]
Closing as this has been implemented for a while now
