### ISSUE TITLE
Record audio

### ISSUE THREAD

**Issue by iclanzan** [roflcoopter/viseron#100]
Many cameras stream audio through the _rtsp_ porotcol in addition to video. Would love it if _viseron_ didn’t discard the audio when recording.

**Comment by roflcoopter** [comment]
Yes this is a good idea. However i dont have a camera to test this with.
When i get the time to implement this, would you be able to test a few things for me?

**Comment by iclanzan** [comment]
Sure thing! Thank you!

**Comment by JustMe0815** [comment]
following as all my cameras have audio support.

**Comment by roflcoopter** [comment]
@iclanzan @JustMe0815 Could either one of you link me the FFmpeg command that is printed to the log when you start Viseron? I will try to adapt it to work with audio aswell, but would be great if you could test it for me first before i implement it in code.
Just redact any credentials in the camera URL before you post

**Comment by JustMe0815** [comment]
@roflcoopter [2021-04-06 14:02:51] [lib.camera.frontdoor    ] [DEBUG   ] - FFMPEG decoder command: ffmpeg -hide_banner -loglevel fatal -avoid_negative_ts make_zero -fflags nobuffer -flags low_delay -strict experimental -fflags +genpts -stimeout 5000000 -use_wallclock_as_timestamps 1 -vsync 0 -rtsp_transport tcp -i rtsp://admin:xyz@192.168.103.10:554/ch0_1.264 -f rawvideo -pix_fmt nv12 pipe:1
[2021-04-06 14:02:51] [lib.nvr.frontdoor       ] [DEBUG   ] - NVR thread initialized

I am currently using the latest beta. Usually the vaapi.

**Comment by roflcoopter** [comment]
> @roflcoopter [2021-04-06 14:02:51] [lib.camera.frontdoor ] [DEBUG ] - FFMPEG decoder command: ffmpeg -hide_banner -loglevel fatal -avoid_negative_ts make_zero -fflags nobuffer -flags low_delay -strict experimental -fflags +genpts -stimeout 5000000 -use_wallclock_as_timestamps 1 -vsync 0 -rtsp_transport tcp -i rtsp://admin:xyz@192.168.103.10:554/ch0_1.264 -f rawvideo -pix_fmt nv12 pipe:1
> [2021-04-06 14:02:51] [lib.nvr.frontdoor ] [DEBUG ] - NVR thread initialized
> 
> I am currently using the latest beta. Usually the vaapi.

Thanks, can you exec into the container and try if this command saves audio to the video? Let it run for a little while
```ffmpeg -hide_banner -loglevel fatal -avoid_negative_ts make_zero -fflags nobuffer -flags low_delay -strict experimental -fflags +genpts -stimeout 5000000 -use_wallclock_as_timestamps 1 -vsync 0 -rtsp_transport tcp -i rtsp://admin:xyz@192.168.103.10:554/ch0_0.264 -c copy /recordings/test-sound.mp4```

**Comment by JustMe0815** [comment]
@roflcoopter i have tried this, it creates a 0KB file and the command stops

**Comment by roflcoopter** [comment]
Okay , can you try this?
```ffmpeg -hide_banner -loglevel info -rtsp_transport tcp -i rtsp://admin:UteplatsDawn123@192.168.30.2:554/Streaming/Channels/101/ -ss 00:00:0.0 -t 10 -c:v copy -c:a copy /recordings/test-sound.mp4``` 

It will run for 10 seconds so dont stop it manually.
Can you also post the complete output of the command?

**Comment by JustMe0815** [comment]
```
[mp4 @ 0x55e6f2856080] Could not find tag for codec pcm_alaw in stream #1, codec not currently supported in container
Could not write header for output file #0 (incorrect codec parameters ?): Invalid argument
Stream mapping:
  Stream #0:1 -> #0:0 (copy)
  Stream #0:0 -> #0:1 (copy)
    Last message repeated 1 times
```

**Comment by JustMe0815** [comment]
replacing -c:a copy with -c:v copy -c:a aac does the trick

**Comment by roflcoopter** [comment]
I see, i guess the audio cant be copied then for some streams and it has to be transcoded.
Thanks for your time, now i know what to work with!

**Comment by JustMe0815** [comment]
No problem, thank you. So it turns out when you create a mkv container, transcoding will not be needed. just when using mp4

**Comment by roflcoopter** [comment]
Interesting, will look into mkv and see what implications it might have

**Comment by roflcoopter** [comment]
@JustMe0815 can you try latest dev build? Audio is supported there.

I tested with an online rtsp stream that has audio, and it successfully recorded sound even with mp4 format. Could you try it out?
Viseron will recognize automatically that the stream has sound so you shouldnt have to configure anything.

If it doesnt work you can try to change `extension` under `recorder` to `mkv` and see if that helps.

**Comment by roflcoopter** [comment]
Closing this as it is implemented
