### ISSUE TITLE
Error for optional variable "Path"

### ISSUE THREAD

**Issue by AbDhops** [roflcoopter/viseron#103]
I am trying to install Viseron:latest.
As defined in documentation (camera configuration), `path` variable is optional. However, if I don't give it, then I get error.
`voluptuous.error.MultipleInvalid: required key not provided @ data['cameras'][0]['path']`

As I have already provided name, host (ip Address), port, stream format, username and password, I was expecting that rtsp link is constructed from this. `rtsp://admin:password@ip_address:554//h264Preview_01_main`

~~I have tried several ways to give path. But every time it failed with error 401 (authentication failure). I have confirmed that the link, login ID and password is correct by using it in VLC.~~ This is resolved. But above issue regarding PATH is still valid. My proposal is to give some more examples in document. e.g. in rtsp path ~~could~~ should be `/h264Preview_01_main`

Can someone help me to know what is wrong and how to move forward. Many thanks.

**Comment by roflcoopter** [comment]
Sorry you are having issues!

```path``` is only optional if your stream is accessible directly from the IP adress of the camera.

What do you suggest for the documentation? Right now its specified pretty much the way you propose it unless i am missunderstanding you.
See snippet below from README

Name | Type | Default | Supported options | Description
-- | -- | -- | -- | --
path | str | optional | any string | Path to the camera stream, eg /Streaming/Channels/101/

**Comment by AbDhops** [comment]
Now when you mentioned it, I see it ! I agree.
Still considering Reolink cameras, link is `rtsp://admin:password@ip_address:554//h264Preview_01_main`. This can not be change. See Reolink documentation [here](https://support.reolink.com/hc/en-us/articles/360007010473-How-to-Live-View-Reolink-Cameras-via-VLC-Media-Player). 
So if someone want to use Reolink cameras, path should be `//h264Preview_01_main`, else it will not work and one will get error shown above. My proposal is to document this for the path.

**Comment by roflcoopter** [comment]
This wont be feasible without having some sort of database with paths for different cameras, which i wont have the time to maintain, i will close this issue
