### ISSUE TITLE
[Feature] Camera checker

### ISSUE THREAD

**Issue by segator** [roflcoopter/viseron#109]
First of all I want to thanks you for your fantastic application!

it will be nice if we can report on sensor/status mqtt path
a new state: connection_lost instead of scanning_for_motion/objects when we lost conection to the cam for any reason.
as then we can use MQTT to send alerts to know that the camera goes down

**Comment by roflcoopter** [comment]
Thanks for the kind words!

Great idea, should be fairly easy to implement
