### ISSUE TITLE
[FR] Substreams with another protocol or port

### ISSUE THREAD

**Issue by mruettgers** [roflcoopter/viseron#112]
Right now substreams can be defined by configuring an alternative path only.
This is not sufficient for devices, that i.e. provide a low-res stream on another port or via another protocol.
My doorbell for example (a Doorbird) provides a high-res stream via RTSP on port 554 and a low-res stream via MJPEG on port 80.
It would be great to have the same connection configuration options for the substream as we have for the main stream.

**Comment by roflcoopter** [comment]
You are correct, will fix

**Comment by roflcoopter** [comment]
This has been resolved in 1.8.0
