### ISSUE TITLE
[FR] have detection mask in recordings

### ISSUE THREAD

**Issue by Sloth-on-meth** [roflcoopter/viseron#119]
Hi there!

i would like to have this tracking box show in the recordings:
https://i.imgur.com/jLUoExH.png

How can i do that

**Comment by roflcoopter** [comment]
Sorry, this is not possible im afraid, the recording is being copied from the input source.

Its not something that can be done easily either, and it will cause huge CPU usage, since Viseron would have to decode every single frame to draw on it, then encode it again.
