### ISSUE TITLE
[FR] Save image of the object detection

### ISSUE THREAD

**Issue by extremeshok** [roflcoopter/viseron#12]
If an object is detected, have an option to save this image, ie capture stills as well as video

**Comment by roflcoopter** [comment]
Thanks for showing interest in Viseron!
Can you elaborate a little, would you like an image to be saved everytime an object is detected?
Right now a thumbnail is generated when a recording starts with the bounding boxes of the triggering objects drawn upon it.
The thumbnail resides in the same folder as the recordings.

**Comment by Backslashh** [comment]
I have a similar request but mine if more for being able to pass the detection image (with bounding boxes) to Home-Assistant to be used in notifications. 

I like sending a notification that a person or car has been detected but also including the image along with the notification.

If this is already possible, please tell me how. 😊

PS. I freaking love this. Once I have it all sorted I'll be able to remove my Deepstack and MotionEye containers!

**Comment by roflcoopter** [comment]
Its not possible currently but i have set things up for this to be fairly easy to implement. What I am thinking is creating a new camera entity in home assistant containing an image of the last detection, and let the user configure what should be drawn (detections, motion, zones etc). Does that sound good to you?

**Comment by Backslashh** [comment]
Yep. It sure does. 
I was just thinking of having the thumbnail image also be written to a [camera.name]_latest.jpg file or something and then in HA just being able to reference the "latest" image would work. That way the file name would be the same everytime. 

But your way works too. 😊

**Comment by rudders** [comment]
Home Assistant Push Platform is handy for this. I use a little broker between shinobi and Push to achieve this and it works great, gives you a few frames..

https://www.home-assistant.io/integrations/push/

**Comment by sdwilsh** [comment]
I'm using 1.8.0b1, and it looks like there's no way to get the image without the detection labels printed on it.  Is it possible to make that configurable as well?

**Comment by roflcoopter** [comment]
yes that could definitely be configurable

**Comment by roflcoopter** [comment]
Closed in v2
