### ISSUE TITLE
viseron exited with code 132

### ISSUE THREAD

**Issue by dadaloop82** [roflcoopter/viseron#125]
### Foreword

Has worked very well, for about 3 months, without ever stopping

### Info

roflcoopter/viseron:latest in Docker (v1.7.2 & 1.8.0b1)
DockerCompose: 1.25.3

### Attempts

1. I recreated the docker image from scratch (failed)
2. I tried to change the configuration (it works only if facial recognition is removed)
3. I tried to remove all the images for the training (failed)
4. I tried to run without the folder /face_recognition/faces (failed)
5.  I tried to run without the folder /face_recognition (failed)

### Log (debug)

```javascript
Creating viseron ... done
Attaching to viseron
viseron    | [2021-02-23 09:10:43] [root                    ] [INFO    ] - -------------------------------------------
viseron    | [2021-02-23 09:10:43] [root                    ] [INFO    ] - Initializing...
viseron    | [2021-02-23 09:10:43] [root                    ] [DEBUG   ] - Starting cleanup scheduler
viseron    | [2021-02-23 09:10:43] [root                    ] [DEBUG   ] - Running initial cleanup
viseron    | [2021-02-23 09:10:43] [lib.cleanup             ] [DEBUG   ] - Running cleanup
viseron    | [2021-02-23 09:10:43] [lib.mqtt                ] [INFO    ] - Initializing MQTT connection
viseron    | [2021-02-23 09:10:43] [lib.detector            ] [DEBUG   ] - Initializing object detector darknet
viseron    | [2021-02-23 09:10:43] [lib.detector            ] [DEBUG   ] - Object detector initialized
viseron    | [2021-02-23 09:10:43] [lib.post_processors     ] [DEBUG   ] - Initializing post processor face_recognition
viseron exited with code 132
```

**Comment by dadaloop82** [comment]
### Problem self resolved

Windows 10's Hyper-V feature, which hosts the Linux virtual machine, conflicts with emulation.
This functionality should be disabled from the Host machine if you are using a virtual machine.

Please close.

**Comment by roflcoopter** [comment]
Glad you got it sorted and thanks for reporting back!
