### ISSUE TITLE
[FR] MQTT on record complete

### ISSUE THREAD

**Issue by JustMe0815** [roflcoopter/viseron#145]
Hi there,

it would be great to get a "recording completed" state including the Path info to the newly created file in
 `{client_id}/{mqtt_name from camera config}/sensor/status/state`

Then we could process the file with for example home automation.

Thanks in advance!

-Dennis

**Comment by roflcoopter** [comment]
Seems reasonable, will add eventually.

**Comment by roflcoopter** [comment]
Closed in v2
