### ISSUE TITLE
[FR] include camera name in recording filename

### ISSUE THREAD

**Issue by akohlsmith** [roflcoopter/viseron#17]
On multiple-camera systems we don't presently have any way of knowing which camera has been recorded to disk.  I really like the directory approach you have. Could we perhaps add a level to it, instead of `recordings/date/file`, perhaps `recordings/camera/date/file`?  Ideally the order of the directory (camera/date or date/camera) would be in the config file, as would the directory and snapshot/video filename templates.

**Comment by roflcoopter** [comment]
Yes this makes total sense. I will see to it in the coming releases.

**Comment by roflcoopter** [comment]
closed in [v1.4.0](https://github.com/roflcoopter/viseron/releases/tag/v1.4.0)
