### ISSUE TITLE
RTMP-camera feeds for Viseron

### ISSUE THREAD

**Issue by quenthal** [roflcoopter/viseron#170]
Suggestions how to configure RTMP-cameras? 

With my current NVR-software input-path for my Reolink-cameras in ffmpeg is rtmp://<<cameraip>>:<<cameraport>>/bcs/channel0_main.bcs?channel=0&stream=0&user=<<usr>>&password=<<passwd>>

Other input arguments are - -avoid_negative_ts - make_zero - -fflags - nobuffer - -flags - low_delay - -strict - experimental - -fflags - +genpts+discardcorrupt - -rw_timeout - '5000000' - -use_wallclock_as_timestamps - '1'

Reason I'm using RTMP from camera, is that RTSP are prone to corrupt and RTMP give more stable fee with these Reolink devices.

**Comment by roflcoopter** [comment]
Closing as this has been implemented
