### ISSUE TITLE
EdgeTPU not found

### ISSUE THREAD

**Issue by windows10luke** [roflcoopter/viseron#173]
I have an EdgeTPU connected to an Intel i5 Mini PC. When running the following command, in the Docker debugging, it says that the EdgeTPU cannot be found.

docker run --privileged -v /root/viseron/recordings:/recordings -v /root/viseron/config:/config -v /etc/localtime:/etc/localtime:ro --name viseron --device /dev/dri -v /dev/bus/usb:/dev/bus/usb roflcoopter/viseron:latest

I have inspected the running container and verified that the /dev/bus/usb is there and contains the proper files. I will also add that I tried running blakeblackshear/frigate and it can find the EdgeTPU with no issues. So, I know it is not an issue with my hardware configuration. Any ideas as to why this may be happening? Thanks!
![Screenshot (133)](https://user-images.githubusercontent.com/40614799/117892700-32f24780-b287-11eb-9dde-92d2fb7da35d.png)

**Comment by roflcoopter** [comment]
Sorry you're having issues.
Can you turn on debug logging and paste the log? 

```yaml
logging:
  level: debug
```

Also it could maybe be a permission issue. Does it work if you add `-e PUID=1000 -e PGID=1000` to your docker command?

**Comment by windows10luke** [comment]
I tried with the following command with no success (with the updated permissions):
docker run --privileged -v /root/viseron/recordings:/recordings -v /root/viseron/config:/config -v /etc/localtime:/etc/localtime:ro --name viseron --device /dev/dri -v /dev/bus/usb:/dev/bus/usb --device /dev/bus/usb -e PUID=1000 -e PGID=1000 roflcoopter/viseron:latest

The error with debugging mode enabled was "Error when trying to load EdgeTPU: Failed to load delegate from libedgetpu.so.1". I am attaching the full EdgeTPU startup log. 

![Screenshot (134)](https://user-images.githubusercontent.com/40614799/118005259-3bdf2980-b318-11eb-9445-41b1a02b231a.png)

**Comment by windows10luke** [comment]
I also tried the last version (1.7.2) of viseron with the following command:
docker run --privileged --name viseron -v /root/viseron/recordings:/recordings -v /root/viseron/config:/config -v /etc/localtime:/etc/localtime:ro -v /dev/bus/usb:/dev/bus/usb --device /dev/bus/usb -e PUID=1000 -e PGID=1000 roflcoopter/viseron-vaapi:1.7.2

This worked without issues.
![Screenshot (135)](https://user-images.githubusercontent.com/40614799/118009893-7e0a6a00-b31c-11eb-9862-ce2005d1d9f0.png)

**Comment by windows10luke** [comment]
I did some more diagnostics and discovered that the permissions is indeed the problem. When setting the PUID and PGID to 0 (root user), it works great with the latest release.
docker run --privileged --name viseron -v /root/viseron/recordings:/recordings -v /root/viseron/config:/config -v /etc/localtime:/etc/localtime:ro -v /dev/bus/usb:/dev/bus/usb --device /dev/bus/usb -e PUID=0 -e PGID=0 roflcoopter/amd64-viseron:latest

There seems to be a problem with a regular, non-root user, having access to the EdgeTPU. I did some research on it, but didn't really find anything that worked. For now, at least it works when it is running as a root user.

**Comment by roflcoopter** [comment]
Ahh interesting, thanks for your elaborate investigation!

I will take a look tomorrow, the newest version is using s6-overlay so it should be possible to fix the permissions before viseron starts

**Comment by roflcoopter** [comment]
@windows10luke A question, can you run `id 1000` on the host and paste the output?
I want to verify if your user is in the `plugdev` group. If it isnt i might be able to fix this by adding the user in the container to this group.

**Comment by windows10luke** [comment]
Sure thing. Here is the output from the terminal. "ndi" is the username that I am currently logged in with.

uid=1000(ndi) gid=1000(ndi) groups=1000(ndi),29(audio),44(video),129(pulse-access)

**Comment by roflcoopter** [comment]
What happens if you run this command:
```
docker run --privileged --name viseron \
-v /root/viseron/recordings:/recordings \ 
-v /root/viseron/config:/config \
-v /etc/localtime:/etc/localtime:ro \
-v /dev/serial:/dev/serial:ro \
--device /dev/bus/usb \
-e PUID=1000 -e PGID=1000 \
roflcoopter/amd64-viseron:latest
```

**Comment by roflcoopter** [comment]
Fixed in dev, permissions are now handled by the s6-overlay.
Would love if you could give it a try at some point

**Comment by windows10luke** [comment]
Was this fixed in the Docker images? I just tried it out with the latest Docker image and it didn't work. I also tried this command with no success finding the EdgeTPU either:
docker run --privileged --name viseron -v /root/viseron/recordings:/recordings -v /root/viseron/config:/config -v /etc/localtime:/etc/localtime:ro -v /dev/serial:/dev/serial:ro --device /dev/bus/usb -e PUID=1000 -e PGID=1000 roflcoopter/amd64-viseron:dev

**Comment by roflcoopter** [comment]
Yes, or atleast I hoped so...
It is working fine for me so it's hard to troubleshoot for me.
While the container is running, can you run these commands?
`docker exec -it viseron ls -lh /dev/bus/usb`

`docker exec -it viseron id abc`

Permissions are very finicky when it comes to USB in docker

**Comment by windows10luke** [comment]
docker exec -it viseron ls -lh /dev/bus/usb returned:
total 0
drwxr-xr-x 2 root root 80 May 16 16:33 001
drwxr-xr-x 2 root root 80 May 16 16:33 002
drwxr-xr-x 2 root root 60 May 16 16:33 003
drwxr-xr-x 2 root root 80 May 16 16:33 004

docker exec -it viseron id abc returned:
uid=1000(abc) gid=1000(abc) groups=1000(abc),44(video),109(video824sYNXl)

These were run while the Docker dev container was running.

**Comment by roflcoopter** [comment]
okay that doesnt look right, user abc needs to have acces to the root group.
what do you get if you run this:
`docker exec -it viseron lsusb`

**Comment by windows10luke** [comment]
This is the output that gets returned with `docker exec -it viseron lsusb`:
Bus 002 Device 002: ID 8087:8000
Bus 002 Device 001: ID 1d6b:0002
Bus 001 Device 002: ID 8087:8008
Bus 001 Device 001: ID 1d6b:0002
Bus 004 Device 002: ID 1a6e:089a
Bus 004 Device 001: ID 1d6b:0003
Bus 003 Device 001: ID 1d6b:0002

**Comment by roflcoopter** [comment]
And if you run `lsusb` directly on the host?

**Comment by roflcoopter** [comment]
Okay now i know whats up.
If i run lsusb i get this output:
```
Bus 001 Device 005: ID 18d1:9302 Google Inc. 
Bus 001 Device 003: ID 0424:ec00 Standard Microsystems Corp. SMSC9512/9514 Fast Ethernet Adapter
Bus 001 Device 002: ID 0424:9514 Standard Microsystems Corp. SMC9514 Hub
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
```
And to find which device is the Google Coral, i grep for Google Inc.
But as you can see, its not displayed for you.

My Coral got the ID 18d1:9302, but apparently some corals can also take the ID of 1a6e:089a which it has in your case.
So my script to fix permissions simply did not pick up your Coral device.

**Comment by roflcoopter** [comment]
I think i might revert back to running as root by default.
Its very important that its easy to get Viseron going and not give a bunch of problems.

Then if you want to not run as root you are free to go down that rabbit hole yourself!

I will change this in the coming days, sorry for your troubles and thanks a lot for the help in investigating.

**Comment by roflcoopter** [comment]
I just pushed a new updated with an improved init script in `/etc/cont-init.d/30-edgetpu-permission` which looks into the udev rules created by the `libedgetpu1-max` package and extracts the vendor ID (currently 18d1 and 1a6e) and makes sure the user has access to these devices. This makes it more future proof if Google changes their vendor ID.

Could you give it a go and see if it works when you run as PUID=1000 and PGID=1000?
Also Viseron will run as root by default

**Comment by roflcoopter** [comment]
Now the build completed successfully

**Comment by windows10luke** [comment]
I just tested it out and it worked great! It was able to find my EdgeTPU without any difficulty, even when it was running with PUID=1000 and PGID=1000. Thanks for all your help with this issue.

**Comment by roflcoopter** [comment]
Great to hear! Thanks for reporting back
