### ISSUE TITLE
better understanding of motion detection

### ISSUE THREAD

**Issue by akohlsmith** [roflcoopter/viseron#18]
Note sure if this should be an Issue or perhaps brought up elsewhere (a forum, Reddit or HA?)

I'm trying to tune the motion detection system, but the logging is creating more questions than answers. :-)

```
[2020-09-10 09:34:36] [lib.motion              ] [DEBUG   ] - Motion frames: 32, area: 285.5
[2020-09-10 09:34:36] [lib.motion              ] [DEBUG   ] - Motion frames: 9, area: 189.0
[2020-09-10 09:34:36] [lib.motion              ] [DEBUG   ] - Motion frames: 25, area: 161.0
[2020-09-10 09:34:36] [lib.motion              ] [DEBUG   ] - Motion frames: 164, area: 562.0
[2020-09-10 09:34:37] [lib.motion              ] [DEBUG   ] - Motion frames: 3, area: 136.0
```

is the `area` value in the same units as in the motion_detection heading in the config file? What about the fames? At 20fps, 164 frames is over two seconds of video, yet I see these messages sometimes a few times per second. How can that be?

Is it possible to have the motion detector spit out images with bounding boxes of where it's seeing video (similar to how the object classifier could spit out an image with a bounding box and label what it identified with confidence level)? This would make tuning the system a lot easier, especially with the ability to send a signal or MQTT message to reload the config file.

**Comment by roflcoopter** [comment]
Sorry about the motion detection being a little unclear to configure.
I need to work a little bit more with the README and explain some more, just need to find the time to do all at once!

The reasing why its spitting out a few times per second depends on what ```interval``` you set. Its a unit in seconds, so 1 means once every second, 0.5 means 2 times per second etc etc

**Comment by akohlsmith** [comment]
Excellent, thank you.

Could you also add something in the README.md describing how labels work? I feel it's a super simple concept but I'm just failing at understanding it. Are they just for-viseron names for the objects?

**Comment by roflcoopter** [comment]
Sorry missed this reply.
Sure i will add som explanations for the labels, but basically they are filters for what objects you want binary sensors/recordings for.
