### ISSUE TITLE
Option to remove colons from filenames - use your own pattern

### ISSUE THREAD

**Issue by gniknalu** [roflcoopter/viseron#182]
I'm finding the filenames are unusable when shared on Samba.

In the logs, for file creation, it shows:
`[2021-05-25 16:38:54] [lib.recorder.frontwest ] [DEBUG ] - Concatenation command: ['ffmpeg', '-hide_banner', '-loglevel', 'error', '-y', '-protocol_whitelist', 'file,pipe', '-f', 'concat', '-safe', '0', '-i', '-', '-c:v', 'copy', '-movflags', '+faststart', '/recordings/2021-05-25/FrontWest/16:38:41.mp4']`

But, because of the colons, the filename in the samba share appears as:
**159ZX1~2.MP4**

In samba they can be mapped to other characters but, even then, they're not opening correctly.

My Question: Is there a way to change the filename so they don't include colon? (Can't find a setting in the documentation as of 2021.05.25) Something like %Y-%m-%d %f

**Comment by roflcoopter** [comment]
This is available now as a new config option under recorder, `filename_pattern`, in the `dev` tag.

You can use it like this for example:
```yaml
recorder:
  filename_pattern: '%H%M%S'  # strftime pattern
```

Which would produce files named `235959.mp4` instead of `23:59:59.mp4`

**Comment by gniknalu** [comment]
Thank you!

**Comment by superfunk2000** [comment]
The filename_pattern option only affects the video file, not the snapshots.
I have configured the following patterns:
filename_pattern: '%H-%M-%S'

In the Windows share it looks like this:
![2023-06-26 11_25_39-2023-06-26](https://github.com/roflcoopter/viseron/assets/90634124/98b9f23e-868a-4a08-a760-c1d87839167e)
