### ISSUE TITLE
Do Not Detect in Privacy Mask Area

### ISSUE THREAD

**Issue by gniknalu** [roflcoopter/viseron#183]
![20210526_privacy_mask_issue](https://user-images.githubusercontent.com/3652809/119705732-b7fc6580-be1e-11eb-9207-185f5006d6ae.jpg)

There is an area where I've applied a privacy mask but it still will detect people/cars in the privacy mask area. (See attached picture - the "car 93%" is inside the privacy mask.) Should object detection respect the privacy mask?

Thank you!

**Comment by roflcoopter** [comment]
Masks only affect zones. You could make a zone with the same coordinates and not track any labels there.

Let me know if that works out for you!

**Comment by gniknalu** [comment]
Not sure if I'm doing it right - I created another zone with the same coordinates  but left the labels blank. That caused this error:

```
voluptuous.error.MultipleInvalid: expected str for dictionary value @ data['cameras'][0]['zones'][1]['labels'][0]['label']
Traceback (most recent call last):
  File "viseron.py", line 8, in <module>
    from lib.config import CONFIG, NVRConfig, ViseronConfig
  File "/src/viseron/lib/config/__init__.py", line 101, in <module>
    CONFIG = VISERON_CONFIG_SCHEMA(raw_config)
  File "/usr/local/lib/python3.6/dist-packages/voluptuous/schema_builder.py", line 272, in __call__
    return self._compiled([], data)
  File "/usr/local/lib/python3.6/dist-packages/voluptuous/schema_builder.py", line 594, in validate_dict
    return base_validate(path, iteritems(data), out)
  File "/usr/local/lib/python3.6/dist-packages/voluptuous/schema_builder.py", line 432, in validate_mapping
    raise er.MultipleInvalid(errors)

```
Then I removed the label entirely and it's just another zone and tracks everything. . . . 

Did I misunderstand what you mentioned?

Thanks!

**Comment by roflcoopter** [comment]
Could you show your config?
Its not supported to NOT look for anything really, but you can workaround this with a config something like this:
```yaml
labels:
  - label: car
    confidence: 1
    triggers_recording: false
```

This will make it so that if a car with 100% accuracy is detected, it will not start a recording.
Is this what you want to achieve? Or what is the end goal?

**Comment by roflcoopter** [comment]
Actually as you can see the detections are marked with a blue square, this means they have been filtered out and will not cause the recorder to trigger. If they instead appear green they will trigger the recorder.

But yeah, as i asked in the previous comment. What is your end goal? MQTT notifications if a car is present but no recordings?

**Comment by gniknalu** [comment]
End goal: Not recording, no MQTT notification. If they're filtered out that is good because I get spammed with the people/cars there. I will make the adjustment to "triggers_recording: false" and will report back. Thank you again!

**Comment by gniknalu** [comment]
It seems to work - I set it to only look for a dog - LOL

Thanks!

**Comment by roflcoopter** [comment]
Haha nice 😎
