### ISSUE TITLE
Support Parsing MJPEG Streams

### ISSUE THREAD

**Issue by nickburns2006** [roflcoopter/viseron#2]
I’ve got an older camera that only has MJPEG streams. Wondering if you have any idea how to get it working in your configurations, or if I need to basically re-write all of the ffmpeg arguments.

I’ll admin I’m not all to familiar with the vast array of ffmpeg arguments...

**Comment by roflcoopter** [comment]
That should (probably) be pretty easy. Do you have an example ffmpeg command at all?
I will add this to my list and will get to it eventually!

**Comment by nickburns2006** [comment]
I think this is one, but I’ll have to test it out when I’m not on mobile:

`ffmpeg -i http://192.168.0.100/mjpeg.cgi -c:v mjpeg -f mjpeg`

**Comment by roflcoopter** [comment]
I added basic mjpeg support in one of the containers dev tag, see #6 . Which docker image are you planning on using?

**Comment by nickburns2006** [comment]
Raspberry Pi.

If it doesn’t work, I’ll attempt to modify and submit a PR

**Comment by roflcoopter** [comment]
Closing this, feel free to open a new issue if you have any problems.
