### ISSUE TITLE
debugging RTSP that ffmpeg isn't happy with

### ISSUE THREAD

**Issue by akohlsmith** [roflcoopter/viseron#20]
I have a bunch of cameras, regular old h264/265 ONVIF cameras from MarvioTech. They work great.

I bought a camera doorbell which has really crappy software. VLC can play the stream fine with `rtsp://admin:xx@192.168.xx.xx:554/onvif1`. I believe I have it set up correctly in Viseron, but this is what I get in the debug log on startup:

```
[2020-09-10 09:47:50] [lib.camera.cam09        ] [DEBUG   ] - FFMPEG decoder command: ffmpeg -hide_banner -loglevel panic -avoid_negative_ts make_zero -fflags nobuffer -flags low_delay -strict experimental -fflags +genpts -stimeout 5000000 -use_wallclock_as_timestamps 1 -vsync 0 -hwaccel vaapi -vaapi_device /dev/dri/renderD128 -rtsp_transport tcp -i rtsp://admin:xx@192.168.xx.xx:554/onvif1 -f rawvideo -pix_fmt nv12 pipe:1
[2020-09-10 09:47:51] [lib.camera.cam09        ] [ERROR   ] - Error starting decoder pipe! [rtsp @ 0x55e6c75d7780] Nonmatching transport in server reply rtsp://admin:xx@192.168.xx.xx:554/onvif1: Invalid data found when processing input
```

I'll see if I can get ffmpeg to dump some frames outside of Viseron, but is there anything more specific I can do to help debug this?

**Comment by roflcoopter** [comment]
A good idea to debug issues with ffmpeg is to exec into the container and run the command with a higher debug level and see what error message you are getting and then turning to google. A quick look at this suggests that camera doesnt like ```-rtsp_transport tcp``` .

Can you try this for me and see if its erroring out?
```docker exec -it viseron ffmpeg -hide_banner -loglevel panic -avoid_negative_ts make_zero -fflags nobuffer -flags low_delay -strict experimental -fflags +genpts -stimeout 5000000 -use_wallclock_as_timestamps 1 -vsync 0 -hwaccel vaapi -vaapi_device /dev/dri/renderD128 -rtsp_transport udp -i rtsp://admin:xx@192.168.xx.xx:554/onvif1 -f null /dev/null```

**Comment by akohlsmith** [comment]
I changed `-loglevel panic` to `debug` and yes, it seems the `-rtsp_transport udp` solved it!  I seem to get ffmpeg processing a bunch of frames, but there are errors still:

```
cur_dts is invalid st:0 (0) [init:0 i_done:0 finish:0] (this is harmless if it occurs once at the start per stream)
    Last message repeated 10 times
[h264 @ 0x55c5d0d26880] nal_unit_type: 1(Coded slice of a non-IDR picture), nal_ref_idc: 3
[h264 @ 0x55c5d0d26880] illegal modification_of_pic_nums_idc 8
[h264 @ 0x55c5d0d26880] decode_slice_header error
[h264 @ 0x55c5d0d26880] no frame!
Error while decoding stream #0:0: Invalid data found when processing input
```

It does seem to work though. If I switch the rtsp_transport back to tcp it fails immediately with the original error.

**Comment by roflcoopter** [comment]
> Error while decoding stream #0:0: Invalid data found when processing input

As long as ffmpeg doesnt exit it should be okay. ffmpeg prints a lot of warnings that can be ignored.

**Comment by mario-tux** [comment]
I got a camera that looks not working well using rtsp/tcp but better with rstp/udp. How can I switch to udp transport (keeping all the other settings of ffmpeg)? It looks embedded in the code when rtsp is used?

**Comment by roflcoopter** [comment]
Yes its hard-coded sadly, totally forgot to include a config option for it in 1.4.0.

I really appreciate all the testing and comments you provide @akohlsmith and @mario-tux it will really help viseron in the long run.

I am not sure if this is the right place to tell you this, but I won't be able to do any fixes in the coming days as I had to have emergency surgery, removing my appendix, so I am still hospitalized. Just wanted to let you guys know that I'm not ignoring you :)

**Comment by mario-tux** [comment]
> I am not sure if this is the right place to tell you this, but I won't be able to do any fixes in the coming days as I had to have emergency surgery, removing my appendix, so I am still hospitalized. Just wanted to let you guys know that I'm not ignoring you :)

Keep care of you!

**Comment by akohlsmith** [comment]
holy cow, that is serious! I am very happy to hear you've received the emergency medical care you needed. Get healthy, software will wait. :-)
