### ISSUE TITLE
[FR] Masks

### ISSUE THREAD

**Issue by mario-tux** [roflcoopter/viseron#21]
I can't see any FR and in the actual "to do" list so I'm requesting this basic, but useful, feature: masking of the frame to suppress motion and/or detection on specific areas of the frame. This should save computational power too.

**Comment by akohlsmith** [comment]
+1; in fact I would NOT do this how Frigate is doing it; they are detecting objects over the entire frame and then if the centre mass is within the white mask area it is detected. I think it might be better to use a more traditional "don't motion detect on any masked areas" so you're not constantly running object detection on frames where it's just the leaves in the trees blowing.

**Comment by blakeblackshear** [comment]
Masked areas are excluded from motion detection in frigate. Objects won't be detected in masked areas unless they start in an unmasked area and are tracked into the masked area. At that point they are ignored as well.

**Comment by roflcoopter** [comment]
I have not quite decided how to implement this yet, zones will partly solve the object detection problem, but atm does nothing for motion detection.

@blakeblackshear Do you feel using masks for the object detection is really necessarry when there are zones to configure? Or is that just how it was implemented in frigate before zones came into the picture?

**Comment by mario-tux** [comment]
Think about it also a way to cut off the computational wastefulness: if I say that such area is out of my interest (trees, public street, ....) why should I spend CPU/Coral cycles to evaluate it?

**Comment by blakeblackshear** [comment]
They aren't that useful for object detection except in a few edge cases.
