### ISSUE TITLE
[FR] MJPEG stream of the cameras

### ISSUE THREAD

**Issue by mario-tux** [roflcoopter/viseron#23]
Frigate exposes several endpoints; I found the realtime MJPEG video (https://github.com/blakeblackshear/frigate#camera_name) very useful flor:
- realtime debug of the engine detection behavior; does Viseron update the MQTT camera when nothing (motion and object) is detected?
- I personally use the MJPEG stream to show the realtime video of the cameras on a Chromecast-like device (a Google Nest Hub Max); it is very useful because there is no lag or delay; HA cameras management is a nightmare from this point of view....

A note: Frigate warns that when the MJPEG stream is used the CPU load spikes but this is fine for my personal type of usage.

I hope this fits in your project idea.

**Comment by roflcoopter** [comment]
Yepp this is a fair feature request. I am already drawing the frames, but sending them to MQTT to be consumed in Home Assistant. Shouldnt be too much work to just restream it to MJPEG instead

**Comment by akohlsmith** [comment]
Do either of you have a neat trick for grabbing and decoding the images sent over MQTT? I can do it manually but perhaps there's an easy utility that I'm not aware of?

**Comment by roflcoopter** [comment]
Just a question on this, right now i draw objects, motion, zones and masks on the image sent to Home Assistant over MQTT. Is this desired here aswell or do you expect to see the frames unedited?

Also the image sent over MQTT is only sent after either the motion detector or object detector has processed a frame, is this okay or do you expect to see every frame? This would cause problems with drawing motion/objects since not every frame is analyzed

**Comment by mario-tux** [comment]
It would be nice to have it configurable. If enabled, it should be enough to have "drawn" only the analyzed frames (blinking effect).

**Comment by roflcoopter** [comment]
Great then I know what to work with, thanks!

**Comment by danielperna84** [comment]
I have just learned about this project and have not yet tried it out (using ZoneMinder currently, but very interested in viseron), but if I may add: an unmodified stream with minimal delay would be great. My usecase would be to stream the video to a Nest Hub when someone rings the doorbell. To be compatible with various camera and display models I can imagine to have multiple configuration options:
- forward original stream from the camera (useful when using VLANs and the display shouldn't be allowed to directly communicate with the camera / view the original stream)
- raw or transcoded original stream to specific format depending on the used display (rtsp, mjpeg, mp4, hls etc.)
- modified stream with options like the objects, masks, custom resolution, output stream format (again rtsp, mjpeg...) etc.

So essentially a way to take whatever input data is available and display it with the least amount of consumed resources, ideally without any transcoding if camera and display share the format, and transcoded if one of the two doesn't match.

**Comment by roflcoopter** [comment]
> I have just learned about this project and have not yet tried it out (using ZoneMinder currently, but very interested in viseron), but if I may add: an unmodified stream with minimal delay would be great. My usecase would be to stream the video to a Nest Hub when someone rings the doorbell. To be compatible with various camera and display models I can imagine to have multiple configuration options:
> 
> * forward original stream from the camera (useful when using VLANs and the display shouldn't be allowed to directly communicate with the camera / view the original stream)
> * raw or transcoded original stream to specific format depending on the used display (rtsp, mjpeg, mp4, hls etc.)
> * modified stream with options like the objects, masks, custom resolution, output stream format (again rtsp, mjpeg...) etc.
> 
> So essentially a way to take whatever input data is available and display it with the least amount of consumed resources, ideally without any transcoding if camera and display share the format, and transcoded if one of the two doesn't match.
> 
> **Edit:**
> Thinking about it, I think it would be nice to do most of this using query parameters. Something like `http://viseron.local/camera1/stream?format=mjpeg&original=1` or `http://viseron.local/camera1/stream?format=webm&objects=1`.

Thanks for showing interest in Viseron! And thanks for the input.
Right now i have the basics down, using query parameters as you described.
However no transcoding is dine right now and its only in mjpeg format. But i feel the transcoding part would be a good addition in the future.

I am sorry this has taken so long to implement, I have had a lot going on with work lately. I do have some vacation now before and after christmas so i will post a new beta with a first implementation of this, problably monday or tuesday

**Comment by danielperna84** [comment]
One more thing that came to my mind that would be nice as a query parameter: rotation and mirroring / flipping the image. Sometimes it's not possible to mount the camera in the direction that would match the display. So it would be nice to be able to do that as well. 👍

**Comment by roflcoopter** [comment]
A first version of this is now available in 1.8.0b1

**Comment by mruettgers** [comment]
Works like a charm 👍.
Thank you!

@mario-tux  May I ask you how you are sending the stream to the  Google Nest device?

**Comment by mario-tux** [comment]
> @mario-tux May I ask you how you are sending the stream to the Google Nest device?

I use catt (https://github.com/skorokithakis/catt) to cast a custom HTML page (+JS) that show all my cameras (using MJPEG).

**Comment by mruettgers** [comment]
The streams of my cameras are working without any problems so far, but in my opinion, it would be better to define the parameters of the streams in the config file, because then we can feed the clients out of the same queue after post-processing the stream. Right now the CPU load increases every time a new client requests the stream. A better approach would be the use of a buffer that is used to feed all of the requests without the need of doing post-processing for each client.
Alternatively the query parameters can be hashed to build a buffer for each unique combination of parameters.

**Comment by roflcoopter** [comment]
Yes this is probably a good idea @mruettgers, heres what im thinking:

```yaml
cameras:
  - name: Front Door
    mjpeg_streams:
      - endpoint: my-mjpeg-stream
        draw_objects: true
```

And then the stream would be accessible at http://ip:port/front-door/my-mjpeg-stream

**Comment by roflcoopter** [comment]
Latest beta release now improves a lot upon this idea.
Static mjpeg streams as suggested by @mruettgers is now available, see [here](https://github.com/roflcoopter/viseron/tree/dev#static-mjpeg-streams) for more information.

There are also more options to process the stream, rotate and mirror as suggested by @danielperna84

**Comment by akohlsmith** [comment]
Not re-opening, just a question about whether it's possible to "layer" video with ffmpeg -- i.e. unedited image as the base layer, with the bounding box/etc. on another layer and have the video player select the base stream or the base+drawing stream? I'm sufficiently inexperienced with ffmpeg and video streaming in general to know if this is a dumb question. :-)

**Comment by roflcoopter** [comment]
I guess it could be done, the problem would lie in trying to sync them up properly.

What's your use case? Are the MJPEG streams not sufficient since they only show "processed" frames?

**Comment by neagix** [comment]
When auth is enabled, how does one access the MJPEG streams?

**Comment by roflcoopter** [comment]
Each camera has a camera access token entity, and that token can be used for this.
However it is frequently renewd so it might not be practical depending on where you consume the stream from.

I am working on a way to create long lived access tokens tho, should be in the next release and in `dev` soon i hope

**Comment by neagix** [comment]
> Each camera has a camera access token entity, and that token can be used for this.
> However it is frequently renewd so it might not be practical depending on where you consume the stream from.

I ended up using this token.
