### ISSUE TITLE
[FR] Concatenation start and end mqtt events/messages 

### ISSUE THREAD

**Issue by Itach1Uchixa** [roflcoopter/viseron#237]
For a short period of time after recording end event emitted, the video recording is not available. It would make integration with other systems/apps easier if there were a concatenation start/end event.

Now, if one tries to use the camera with other services, it's impossible to know when other services can use/move/copy video recordings because after the viseron emits a camera status change message from recording to other state (recording end event), there are problems described below:

1. the video recording file has not yet been created (it tooks about 1 second tested it myself)
2. the video recording file exists, but the concatenation proccess is not ended yet

It would be great if event I described above will have created file paths in it

**Comment by roflcoopter** [comment]
The delay is there for technical reasons so it cannot be avoided unfortunately.

I think the best way to solve this is to send a separate event after the recording has finished encoding, would that be helpful?

**Comment by Itach1Uchixa** [comment]
Is it possible to send event after concatenation process finished?

**Comment by roflcoopter** [comment]
At the moment no, but its something i can implement

**Comment by roflcoopter** [comment]
Closed in v2, videos are now encoded in a temp folder and moved to the final location when its done

**Comment by AntonVonDelta** [comment]
Hi! I was trying to do the same - reading the video after recording stopped inside a docker machine. However it seems the file is not completed when mqtt event is fired and I sometimes get 46bytes or ~50bytes. If I were to wait longer more of the file would be completed.

I thought that ffmpeg would lock the file so I tried to wait until I could get a write lock on the file but it seems I just took the lock without any delay or bugs.

Can you please point me to the area of code responsable with this? Your fix for me didn't work.

**Comment by roflcoopter** [comment]
It is this section right here: https://github.com/roflcoopter/viseron/blob/c441207450029fa0a1e6a3e17ef7c822efa9274b/viseron/components/ffmpeg/segments.py#L291-L309

There are actually two events at play here, one that is fired when the recorder stops (which is too soon to grab the video) and then there is the other event in the linked code.

This second event is not emitted to mqtt sadly, will make sure to fix that soon!
