### ISSUE TITLE
MQTT sensor/[cam_name]/state has empty set

### ISSUE THREAD

**Issue by akohlsmith** [roflcoopter/viseron#24]
I'm using MQTT Explorer to watch what's going on on the MQTT side of things.

I've noticed that when objects are detected, the `detections` list is either "`null`" or an empty set "`[ ]`".

Is this expected? I thought perhaps it would show the names of the objects detected and perhaps their confidence level.

**Comment by akohlsmith** [comment]
just an addendum -- are there plans for an MQTT topic which would give the same kind of output you can get in the debug log:

```
[2020-09-10 18:54:48] [lib.detector            ] [DEBUG   ] - [{'label': 'car', 'confidence': 0.649, 'height': 0.046, 'width': 0.089, 'relative_x1': 0.344, 'relative_y1': 0.317, 'relative_x2': 0.433, 'relative_y2': 0.363}]
```

**Comment by roflcoopter** [comment]
Yes right now an empty list is always provided.
I am doin a big refactor of how MQTT is working under the 1.4.0 beta. When this is done, or soon in the future, i will start sending detections to MQTT.

However i am not sure at what frequency, should it be only during recordings perhaps? Or just the objects that triggered the recording? If i would send the objects on every detection it would spam MQTT quite hard and fill up the Home Assistant database.

**Comment by mario-tux** [comment]
> However i am not sure at what frequency, should it be only during recordings perhaps? Or just the objects that triggered the recording? If i would send the objects on every detection it would spam MQTT quite hard and fill up the Home Assistant database.

For sure you should trigger two events related to the recordings: started/ended. These should report enough data to locale image and video paths. For the rest you could maintain two MQTT sensors for each camera: motion detection and object detection (with details in attributes). The Frigate zone-related MQTT sensors are interesting too.

**Comment by akohlsmith** [comment]
Definitely agree with @mario-tux here; let those who want noisy events get 'em, and anyone who doesn't want 'em can filter them out. It'll help a LOT with tuning and debugging.

**Comment by roflcoopter** [comment]
Closed in v2
