### ISSUE TITLE
Helm chart

### ISSUE THREAD

**Issue by kevinrademan** [roflcoopter/viseron#241]
Is there any plans to create a helm chart for this project?

**Comment by roflcoopter** [comment]
I have never used Kubernetes so i dont really know how to create one.
I would gladly accept a PR for it tho if you wanna give it a try

**Comment by carlosrodfern** [comment]
(... three years later)

I have it running on kubernetes. I just migrated it to a helm chart and began to work on it here: https://github.com/carlosrodfern/viseron-helm-chart

I'll be working on cleaning it up to make it more generic, and set up CI/CD.

Once I have it ready, @roflcoopter you could then fork it and tweak it for your github repo (it'll be using githup actions) to make it "official". At that point, I can switch to use yours and contribute to it.

I'll post back when I have the first version fully ready.

**Comment by roflcoopter** [comment]
Awesome, thank you! 🚀

**Comment by carlosrodfern** [comment]
> Awesome, thank you! 🚀

Thank **you** for building this awesome app.

I have the helm chart ready, and I have been using it for my installation. It has CI on PRs doing linting and testing, and automatic releasing on merges to `main`, using the github pages. Let me know what you think.

The only thing I have not documented is how to use it with Nvidia. Setting up the nvidia runtime on `containerd` is a little bit of work, which I can't test because I don't have that hardware. Since it is not something trivial, and I can't test it, I passed on documenting how to do it with kubernetes (e.g., k3s.io) and this chart. Hoping someone will, and contribute back to the docs and the chart.

**Comment by roflcoopter** [comment]
> I have the helm chart ready, and I have been using it for my installation. It has CI on PRs doing linting and testing, and automatic releasing on merges to `main`, using the github pages. Let me know what you think.

Had a quick look but i dont fully understand the process, how does Github pages come into play and what is published there?


> I looked into the code and the webserver component, and I can't find any health check endpoint. Is there one? It would be for kubernetes which uses it to decide when it is ready to receive traffic, and if it needs to be restarted/rescheduled.

No healthcheck endpoint is available atm sadly, will make sure to add it!

**Comment by carlosrodfern** [comment]
> Okay i think i get it now. Does it make any sense to keep it in the main repo or should i create a separate repo for it you think?

I recommend you keep it in a separate repository. It is in reality a separate project that can have a very different change pace than your main application. The CI/CD will also be different and may get in your way of your main project.

So, apparently, I have two options. I can transfer the ownership to you (simpler?), or you can fork it, and then I nuke mine and yours become the upstream repo according to github docs. Not sure what the difference is in practice.

**Comment by roflcoopter** [comment]
I see, yes you can try to transfer the ownership, seems simpler indeed!

**Comment by carlosrodfern** [comment]
> I see, yes you can try to transfer the ownership, seems simpler indeed!

You should have gotten a request to accept the transfer. After the transfer is done, we will need to test the github workflows. I can create a PR against the repo to test the ci, and then once merged, we will see if the gh pages is updated with the new version of the chart.

**Comment by roflcoopter** [comment]
Great! Transfer is complete now: https://github.com/roflcoopter/viseron-helm-chart

**Comment by roflcoopter** [comment]
Sorry for the delay in response!

Awesome, great job on this!
Thanks for wanting to make that post, more recognition for Viseron is always welcome.

Will have to update the docs as well to highlight the helm chart

**Comment by roflcoopter** [comment]
I am closing this issue now since the helm chart now exists
