### ISSUE TITLE
Missing file on arm64

### ISSUE THREAD

**Issue by Gsonovb** [roflcoopter/viseron#263]
I tested the nanopc-t4 device (similar to raspberry ) and found that it could not be started.

Check the log and find that the prompt is missing files

```

FileNotFoundError: [Errno 2] No such file or directory: '/detectors/models/darknet/coco.names'
[cont-finish.d] executing container finish scripts...
```

Check that there is only `/detectors/ Models/ edgetpu" directory in the container,

Where do I need the documents?

Also, is there a GUI configuration interface? thank you.

**Comment by roflcoopter** [comment]
Whats the specs on that machine?
The RPi arm64 image is built with the intention to use an EdgeTPU for object detection, as they might be a bit too weak to run Darknet YOLO detection.

If you want to give it a go anyway you can download the needed files and mount them in the container:

```
wget https://github.com/AlexeyAB/darknet/releases/download/darknet_yolo_v4_pre/yolov4-tiny.weights
wget https://raw.githubusercontent.com/AlexeyAB/darknet/master/cfg/yolov4-tiny.cfg
wget https://raw.githubusercontent.com/AlexeyAB/darknet/master/cfg/coco.names

**Comment by Gsonovb** [comment]
This is the device information：  https://wiki.friendlyarm.com/wiki/index.php/NanoPC-T4



I tested it and it didn't start.

Several suggestions

1. Add user interface or visual configuration generation tool

2. When there is an error in the configuration file, a friendly prompt will be displayed

3. Provide some complete configuration file samples
