### ISSUE TITLE
[B] No reconnect if camera stream broken

### ISSUE THREAD

**Issue by oliverqn** [roflcoopter/viseron#270]
When the configured camera is offline (unplugged or not network not reachable) the stream/connection is broken. You do have to restart viseron to reconnect to the camera. It should try to reconnect automatically with a keep alive.

**Comment by roflcoopter** [comment]
This shouldnt be a problem, Viseron is meant to try to reconnect infinitely.

Could you post a log around the time of the disconnect?

**Comment by oliverqn** [comment]
Sure. This is the log when camera gets unplugged.
`viseron      | [2021-09-23 15:50:09] [ERROR   ] [viseron.camera.arbeitszimmer] - FFmpeg process has exited
viseron      | [2021-09-23 15:50:20] [ERROR   ] [viseron.camera.stream.arbeitszimmer] - [tcp @ 0x559c163860] Connection to tcp://192.168.8.26:554?timeout=5000000 failed: No route to host
viseron      | [2021-09-23 15:50:20] [ERROR   ] [viseron.camera.stream.arbeitszimmer] - rtsp://192.168.8.26:554/s0: No route to host
viseron      | [2021-09-23 15:50:20] [ERROR   ] [viseron.camera.arbeitszimmer] - FFmpeg process has exited
viseron      | [2021-09-23 15:50:25] [ERROR   ] [viseron.camera.arbeitszimmer] - Restarting frame pipe
viseron      | [2021-09-23 15:50:32] [ERROR   ] [viseron.camera.stream.arbeitszimmer] - [tcp @ 0x5567bf2860] Connection to tcp://192.168.8.26:554?timeout=5000000 failed: No route to host
viseron      | [2021-09-23 15:50:32] [ERROR   ] [viseron.camera.stream.arbeitszimmer] - rtsp://192.168.8.26:554/s0: No route to host
viseron      | [2021-09-23 15:50:32] [ERROR   ] [viseron.camera.arbeitszimmer] - FFmpeg process has exited
viseron      | [2021-09-23 15:50:37] [ERROR   ] [viseron.camera.arbeitszimmer] - Restarting frame pipe
viseron      | [2021-09-23 15:50:41] [ERROR   ] [viseron.camera.stream.arbeitszimmer] - [tcp @ 0x55b0a2a860] Connection to tcp://192.168.8.26:554?timeout=5000000 failed: No route to host
viseron      | [2021-09-23 15:50:41] [ERROR   ] [viseron.camera.stream.arbeitszimmer] - rtsp://192.168.8.26:554/s0: No route to host
viseron      | [2021-09-23 15:50:41] [ERROR   ] [viseron.camera.arbeitszimmer] - FFmpeg process has exited`

And when plugging in the camera again...
`[2021-09-23 15:52:16] [ERROR   ] [viseron.camera.stream.arbeitszimmer] - Error starting decoder command! NvMMLiteOpen : Block : BlockType = 261 
viseron      | NVMEDIA: Reading vendor.tegra.display-size : status: 6 
viseron      | NvMMLiteBlockCreate : Block : BlockType = 261 
viseron      |  Retrying in 5 seconds, message repeated 3 times
[2021-09-23 15:52:44] [ERROR   ] [viseron.camera.stream.arbeitszimmer] - Error starting decoder command! NvMMLiteOpen : Block : BlockType = 261 
viseron      | NVMEDIA: Reading vendor.tegra.display-size : status: 6 
viseron      | NvMMLiteBlockCreate : Block : BlockType = 261 
viseron      |  Retrying in 5 seconds, message repeated 7 times`

Setup running on jetson nano (jetpack 4.6 L4T 32.6.1) as docker compose stack in conjunction with deepstack.

**Comment by roflcoopter** [comment]
Hmm as you can see Viseron is trying to reconnect, but the error appears to be in the FFMPEG decoder for the Nano.
Can you exec into the container when its in this state and see if there are any leftover ffmpeg processes that take up resources?

**Comment by oliverqn** [comment]
Sorry for late response... I did a `ps aux` in running container.

Thats what I got when camera is connected

> root@cb1a476597eb:/src# ps aux
> USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
> root         1  0.0  0.0    192     0 ?        Ss   08:32   0:00 s6-svscan -t0 /var/run/s6/services
> root        35  0.0  0.0    192     0 ?        S    08:32   0:00 s6-supervise s6-fdholderd
> root       313  0.0  0.0    192     0 ?        S    08:32   0:00 s6-supervise viseron
> root       315 29.1 10.0 2853124 407524 ?      Ssl  08:32   2:13 python3 -u -m viseron
> root       358 18.3  3.7 452924 151668 ?       Sl   08:32   1:23 arbeitszimmer -hide_banner -loglevel error -avoid_negative_ts make_zero -fflags n
> root       369 12.3  3.7 453160 153720 ?       Sl   08:32   0:55 keller -hide_banner -loglevel error -avoid_negative_ts make_zero -fflags nobuffer
> root       396  0.0  0.0   3784  3000 pts/0    Ss   08:38   0:00 bash
> root       417  0.0  0.0   5288  2400 pts/0    R+   08:40   0:00 ps aux

And thats what I got when camera has been disconnected

> root@cb1a476597eb:/src# ps aux
> USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
> root         1  0.0  0.0    192     0 ?        Ss   08:32   0:00 s6-svscan -t0 /var/run/s6/services
> root        35  0.0  0.0    192     0 ?        S    08:32   0:00 s6-supervise s6-fdholderd
> root       313  0.0  0.0    192     0 ?        S    08:32   0:00 s6-supervise viseron
> root       315 27.1 10.6 3074576 433252 ?      Ssl  08:32   3:10 python3 -u -m viseron
> root       369 12.8  3.7 453160 153724 ?       Sl   08:32   1:29 keller -hide_banner -loglevel error -avoid_negative_ts make_zero -fflags nobuffer
> root       396  0.0  0.0   3784  3000 pts/0    Ss   08:38   0:00 bash
> root       457  1.6  0.0      0     0 ?        Z    08:44   0:00 [arbeitszimmer] <defunct>
> root       462  0.0  0.0   5288  2428 pts/0    R+   08:44   0:00 ps aux

**Comment by oliverqn** [comment]
<img width="1023" alt="Bildschirmfoto 2021-09-27 um 08 46 00" src="https://user-images.githubusercontent.com/26775019/134857799-1da5f28f-e86c-45a5-8920-9773d80751b1.png">

**Comment by roflcoopter** [comment]
Closed in v2, failed processes are cleaned up better. Please open a new issue if you still are having problems
