### ISSUE TITLE
After reboot EdgeTPU not found 

### ISSUE THREAD

**Issue by lyncker** [roflcoopter/viseron#284]
After reboot the viseron container starts automaticly, but in this case always the EdgeTPU is not found: 
[ERROR   ] [viseron.detector.edgetpu] - EdgeTPU not found. Detection will run on CPU

If I restart it with dockercommand restart , everything works fine... this happens in my Raps4 enviroment as well as my Rasp3 env where I had the installation bevore... 
any ideas?

**Comment by roflcoopter** [comment]
Closed in v2, please open a new issue if you still experience problems
