### ISSUE TITLE
[DOC] object_detection and motion_detection intervals

### ISSUE THREAD

**Issue by akohlsmith** [roflcoopter/viseron#29]
Two questions:

1. `interval` is how often to run the specified detection. Does that mean that all the frames between the last run and this run will be analyzed, or only a few frames around this point in time will be analyzed? e.g. if I have `motion_detection:interval: 1.0` and my camera is running at 30fps then the motion detection interval will look at the last 30 frames every second to find motion, or only the last `frames: x` number of frames to see if any motion occurred?

I believe that I understand clearly that with `motion_detection:trigger: true` then object_detection will not run unless motion is detected. Otherwise, object detection will run every `interval` seconds (with the same question about how many frames are analyzed). Is that the case?

2. The note under `interval` for `object_detection` states "For optimal performance this should the same as motion detection interval." Is this only true when `motion_detection:trigger` is false?

**Comment by roflcoopter** [comment]
1. Detection runs only on one frame, so if you have a camera with 30 fps and ```interval: 1```, every 30th frame will be scanned.

2. If either ```timeout``` or ```trigger``` under motion detection is true, the intervals should match up (or atleast be divisible by eachother, gonna make a note in the README for that). That is because a lot of processing has to be done on each frame before its ready to run either motion or object detection on. If these two are in sync, that processing only happens once for the frame.

**Comment by akohlsmith** [comment]
Regarding 1: Ok, the `interval: 1` is easy to understand.  Let's try with 30fps and `interval: 10`.   On the tenth frame motion detection will be run: does it compare every tenth frame to see if anything moved (e.g. essentially looking at a 3fps video in my example) or does it look at the last ten frames to see if anything moved?  I guess my question is does `interval` set the motion detector's video stream fps, or does it simply set how many frames are "batched up" and compared at a time? I'm pretty sure it's the first one (i.e. it essentially provides a "camera fps / interval" video stream to the motion detector).

question 2's clear now. Thank you for clearing that up.

**Comment by roflcoopter** [comment]
Only one frame is scanned, they are not bunched up.

```interval``` is a value in **seconds**, and its not tied to the fps in any way. ```interval: 10``` will run ever **10** seconds which is probably not what you want.

If you have a camera with 30fps and you want to run detection on **every** frame(might be a bit too CPU intensive) you would set ```interval``` to 1/30=0.333. Or say you want it to run every other third frame you would set it to 1/(30/3)=0.1.

This might be a bit confusing and maybe having ```interval``` be basically FPS instead would make more sense

**Comment by akohlsmith** [comment]
No, I like the interval as it is and I understand how it operates;  if the camera outputs 30fps and I want object detection 10 times per second I set `interval: 0.1` to achieve that (basically taking every third frame from the stream and essentially doing a "diff" of the two images to see how much has changed. If the number of pixels that has changed is more than `area * width * height` of the motion_detected image, then we call that a motion event. If `trigger` is true, then we run the object detector (on which frames, that's something I asked in #22).
