### ISSUE TITLE
[FR] - Object detection resizing

### ISSUE THREAD

**Issue by jaburges** [roflcoopter/viseron#3]
some cameras have huge resolutions. It would be good to resize those for object detection

**Comment by jaburges** [comment]
looks like you may be trying to resize:
```yaml
cv2.error: OpenCV(4.4.0-dev) /tmp/opencv-master/modules/imgproc/src/resize.cpp:3932: error: (-215:Assertion failed) inv_scale_x > 0 in function 'resize'
````

**Comment by roflcoopter** [comment]
Yes it is resizing the frames to the dimensions of the supplied detection model.
You can specify the ```model_width``` and ```model_width``` in the config.yaml to override this however.

That error doesnt seem right, what resolution are you running your cameras at?

**Comment by roflcoopter** [comment]
Seems like a regression error, im looking at it now

**Comment by roflcoopter** [comment]
The resizing issue is fixed in [this commit](https://github.com/roflcoopter/viseron/commit/9b2ec5598ec4100c25e944dde576f4cbc9377252)

**Comment by jaburges** [comment]
i can confirm manually changing `config_motion_detection.py` per your commit fixes the issue

**Comment by roflcoopter** [comment]
I just pushed the images again.
I think i had an error in my build scripts.
At the moment im building the images locally and pushing to docker hub since im compiling stuff from source.

Can you try again?

**Comment by jaburges** [comment]
yep, that seems to have done it - closing
