### ISSUE TITLE
[DOC] does "area" scale with image size?

### ISSUE THREAD

**Issue by akohlsmith** [roflcoopter/viseron#30]
Just looking for clarification on `motion_detection: area` - is this in square pixels? is it normalized somehow?

e.g. with `height: 300`, `width: 300` and `area: 1000` the area is approximately 1.1% of the image.  With `height: 640`, `width: 360` and the same `area: 1000`, that area is now only 0.43% of the image.

If this is true, would it make better sense to specify area in percent?

**Comment by roflcoopter** [comment]
Yes it is in square pixels.
Keeping it relative just like how min/max width/height works under ```labels``` would make a lot more sense, looking into it.
