### ISSUE TITLE
[FR] Face recognition message to include camera name

### ISSUE THREAD

**Issue by bitbrain-za** [roflcoopter/viseron#311]
When a face detection message is sent, could the attributes be populated with the camera where the frame originated?

Loving the project. Superb work!

**Comment by roflcoopter** [comment]
Absolutely, will add it to the list of features for [v2](https://github.com/roflcoopter/viseron/pull/306)

**Comment by roflcoopter** [comment]
In the next version you get one sensor per camera, is that enough or do you still need the camera name to be in the attributes?

**Comment by bitbrain-za** [comment]
Sorry for the delayed response, that's amazing! Thank you :)

**Comment by roflcoopter** [comment]
Closed in v2
