### ISSUE TITLE
Modularized :: Getting Stream Information For http :: Should look @ rtsp

### ISSUE THREAD

**Issue by gniknalu** [roflcoopter/viseron#320]
I'm seeing this error:
`Getting stream information for http://*****:*****@xxx.xxx.xxx.xxx:`

It's looking for "**http**" instead of "**rtsp**"
Where did I go wrong in my config?

Thank you

**Comment by roflcoopter** [comment]
Saw in your other issue that you had `stream_format: mpeg4`, you should probably remove that

**Comment by gniknalu** [comment]
Fixed. Thank you.
