### ISSUE TITLE
yuv420p & h264_nvmpi missing

### ISSUE THREAD

**Issue by dadaloop82** [roflcoopter/viseron#326]
I have a Jetson Nano 2Gb and about 5 months ago I successfully ran Viseron - which I think is one of the best NVR programs with facial recognition.
Then I had to uninstall it to make space for new projects.

Now, however, I could use it but whatever version I download tells me I'm missing a decoder.
I haven't followed all the comments, so excuse me for asking a question that has already been asked.
Is there anything I can do to fix this and get it working?
Thanks!

I would like to stay at the moment on the stable and released version, but I wanted to try also the 2.0 out of curiosity

roflcoopter/jetson-nano-viseron:latest
roflcoopter/jetson-nano-viseron:dev
```
[2022-02-15 15:10:29] [ERROR   ] [viseron.camera.stream.soggiorno] - [h264_nvmpi @ 0x55cca66ff0] Invalid Pix_FMT for NVMPI Only yuv420p is supported
[2022-02-15 15:10:29] [ERROR   ] [viseron.camera.stream.soggiorno] - Error while opening decoder for input stream #0:0 : Invalid data found when processing input
[2022-02-15 15:10:29] [ERROR   ] [viseron.camera.soggiorno] - FFmpeg process has exited
```

Version 2.0
roflcoopter/aarch64-viseron:modularize
`[2022-02-15 11:34:55] [ERROR   ] [viseron.components.ffmpeg.stream.soggiorno] - Unknown decoder 'h264_nvmpi'`

**Comment by roflcoopter** [comment]
I am refactoring the Nano image, as the current one is very hacky and thus unstable.
To solve this temporarily you can add `codec: h264` to the camera to run without hardware acceleration.

I need someone to run some tests for me on the new builds, could you be of help?

**Comment by dadaloop82** [comment]
> I need someone to run some tests for me on the new builds, could you be of help?

Absolutely yes, helpful and happy to help you!
As I said, I have an Nvidia Jetson Nano Developer Kit 2gb with the original Jetpack operating system.
Here the Features of my Device: https://developer.nvidia.com/embedded/jetson-nano-developer-kit

Do I have to subscribe to a particular channel/thread ?

**Comment by roflcoopter** [comment]
Great! Ill just ping you in this issue.

Could you run this and show me the output?
`docker run --it -rm --runtime=nvidia roflcoopter/jetson-nano-base:test ffmpeg -hwaccels`

**Comment by roflcoopter** [comment]
Interesting.
What about this?
`docker run -it --rm --runtime=nvidia roflcoopter/jetson-nano-base:1.3 ffmpeg -codecs`

**Comment by roflcoopter** [comment]
And this?
`docker run -it --rm --runtime=nvidia roflcoopter/jetson-nano-base:1.3 ffmpeg -decoders`

**Comment by dadaloop82** [comment]
is attached  :)
[decodecs.txt](https://github.com/roflcoopter/viseron/files/8097190/decodecs.txt)

**Comment by roflcoopter** [comment]
wow seems to be working(!)

**Comment by eldadh** [comment]
Any Way to help?
I used to run viseron on Jetson Nano 2G and now i am receiving the similar issues with some of the issues
mainly at the moment :
NvMMLiteOpen : Block : BlockType = 261 
NVMEDIA: Reading vendor.tegra.display-size : status: 6 
NvMMLiteBlockCreate : Block : BlockType = 261

**Comment by roflcoopter** [comment]
> Any Way to help? I used to run viseron on Jetson Nano 2G and now i am receiving the similar issues with some of the issues mainly at the moment : NvMMLiteOpen : Block : BlockType = 261 NVMEDIA: Reading vendor.tegra.display-size : status: 6 NvMMLiteBlockCreate : Block : BlockType = 261

Sorry you're having issues as well.
dadaloop82 offered to give me access to his Nano so i can run some tests

**Comment by eldadh** [comment]
if it helps i could to the same i guess,
although i would prefer the "ping& pong" approach
like we did in the early stages of the nano developent
where you gave us instructions and viewed to corresponding logs.

**Comment by roflcoopter** [comment]
Closed in v2, you can use the `gstreamer` component instead of `ffmpeg` now
