### ISSUE TITLE
OpenCV No Cuda Support

### ISSUE THREAD

**Issue by bailboy91** [roflcoopter/viseron#339]
After switching to a quadro k620 and use the cuda docker container i am getting the below error.  Using  vaapi only everything works correctly.  Using cuda will not work what so ever. Is the K620 too old? Am i using the wrong verion of cuda(11.6) on the host? ``

the host machine is Ubuntu 20.04.4 with cuda 11.6 and nvidia driver 510.  using nvidia-smi i can see that viseron is running.
```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 510.47.03    Driver Version: 510.47.03    CUDA Version: 11.6     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Quadro K620         On   | 00000000:02:00.0 Off |                  N/A |
| 34%   39C    P0     2W /  30W |    587MiB /  2048MiB |      8%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A      3634      G   /usr/lib/xorg/Xorg                 60MiB |
|    0   N/A  N/A      4235      G   /usr/bin/gnome-shell                4MiB |
|    0   N/A  N/A    202336      C   python3                           412MiB |
|    0   N/A  N/A    202578      C   viseron_front                     101MiB |
+-----------------------------------------------------------------------------+
```

In the container i get:
```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 510.47.03    Driver Version: 510.47.03    CUDA Version: 11.6     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Quadro K620         On   | 00000000:02:00.0 Off |                  N/A |
| 33%   39C    P0     2W /  30W |    546MiB /  2048MiB |      1%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A      3634      G                                      60MiB |
|    0   N/A  N/A      4235      G                                       4MiB |
|    0   N/A  N/A    202336      C                                     372MiB |
|    0   N/A  N/A    202578      C                                     101MiB |
+-----------------------------------------------------------------------------
```

in the container checking opencv_version --opencl i get the following:

```
src# opencv_version --opencl
4.5.3
OpenCL Platforms: 
    NVIDIA CUDA
        dGPU: Quadro K620 (OpenCL 3.0 CUDA)
Current OpenCL device: 
    Type = dGPU
    Name = Quadro K620
    Version = OpenCL 3.0 CUDA
    Driver version = 510.47.03
    Address bits = 64
    Compute units = 3
    Max work group size = 1024
    Local memory size = 48 KB
    Max memory allocation size = 500 MB 240 KB
    Double support = Yes
    Half support = No
    Host unified memory = No
    Device extensions:
        cl_khr_global_int32_base_atomics
        cl_khr_global_int32_extended_atomics
        cl_khr_local_int32_base_atomics
        cl_khr_local_int32_extended_atomics
        cl_khr_fp64
        cl_khr_3d_image_writes
        cl_khr_byte_addressable_store
        cl_khr_icd
        cl_khr_gl_sharing
        cl_nv_compiler_options
        cl_nv_device_attribute_query
        cl_nv_pragma_unroll
        cl_nv_copy_opts
        cl_khr_gl_event
        cl_nv_create_buffer
        cl_khr_int64_base_atomics
        cl_khr_int64_extended_atomics
        cl_nv_kernel_attribute
        cl_khr_device_uuid
        cl_khr_pci_bus_info
        cl_khr_external_semaphore
        cl_khr_external_memory
        cl_khr_external_semaphore_opaque_fd
        cl_khr_external_memory_opaque_fd
    Has AMD Blas = No
    Has AMD Fft = No
    Preferred vector width char = 1
    Preferred vector width short = 1
    Preferred vector width int = 1
    Preferred vector width long = 1
    Preferred vector width float = 1
    Preferred vector width double = 1
    Preferred vector width half = 0
```
The error in the container console window:

```
cv2.error: OpenCV(4.5.3) /tmp/opencv/modules/dnn/src/dnn.cpp:2385: error: (-216:No CUDA support) OpenCV was not built to work with the selected device. Please check CUDA_ARCH_PTX or CUDA_ARCH_BIN in your build configuration. in function 'initCUDABackend'

Exception in thread object_detection:

Traceback (most recent call last):

  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner

    self.run()

  File "/usr/lib/python3.8/threading.py", line 870, in run

    self._target(*self._args, **self._kwargs)

  File "/src/viseron/detector/__init__.py", line 105, in object_detection

    frame_to_scan.frame.objects = self.object_detector.return_objects(

  File "/src/viseron/detector/darknet/__init__.py", line 102, in return_objects

    labels, confidences, boxes = self.model.detect(
```

with debug on i see this information as well for object detection:

```
[2022-04-05 19:26:23] [DEBUG   ] [viseron.watchdog.thread_watchdog] - Thread object_detection is dead, restarting

[2022-04-05 19:26:23] [DEBUG   ] [viseron.detector        ] - Frame is 6.310928583145142 seconds old for viseron_front.object_detection. Discarding

[2022-04-05 19:26:23] [DEBUG   ] [viseron.detector        ] - Frame is 5.405937910079956 seconds old for viseron_front.object_detection. Discarding

[2022-04-05 19:26:23] [DEBUG   ] [viseron.detector        ] - Frame is 4.360054969787598 seconds old for viseron_front.object_detection. Discarding

[2022-04-05 19:26:23] [DEBUG   ] [viseron.detector        ] - Frame is 3.31296968460083 seconds old for viseron_front.object_detection. Discarding

[2022-04-05 19:26:23] [DEBUG   ] [viseron.detector        ] - Frame is 2.3976545333862305 seconds old for viseron_front.object_detection. Discarding
```

finally the debug ffmpeg command string:
`
[2022-04-05 19:26:12] [DEBUG   ] [viseron.camera.stream.viseron_front] - FFMPEG decoder command: viseron_front -hide_banner -loglevel error -avoid_negative_ts make_zero -fflags nobuffer -flags low_delay -strict experimental -fflags +genpts -use_wallclock_as_timestamps 1 -vsync 0 -stimeout 5000000 -c:v h264_cuvid -rtsp_transport tcp -i rtsp://192.168.1.163:8554/video3_unicast -f segment -segment_time 5 -reset_timestamps 1 -strftime 1 -c:v copy -c:a copy /segments/viseron-front/%Y%m%d%H%M%S.mp4 -filter:v fps=1 -f rawvideo -pix_fmt nv12 pipe:1`

camera config:

```
cameras:
  - name: viseron-front
    host: 192.168.1.xxx
    port: 8554
    username:
    password:
    path: /video3_unicast
    fps: 15
    width: 1920
    height: 1080
    stream_format: rtsp
    publish_image: true
    mqtt_name: viseron_front
    motion_detection:
      interval: 1
      trigger_detector: false
    object_detection:
      interval: 1
      labels:
        - label: person
          confidence: 0.9
```

**Comment by bailboy91** [comment]
I am thinking that a kepler gen quadro is not supported past cuda 10.1.  I am getting older drivers installed on the host.

**Comment by bailboy91** [comment]
Wondeful, Thank you!  As soon as you let me know I'll try it out.

**Comment by roflcoopter** [comment]
This is now fixed in #306

Could you give it a try?

**Comment by bailboy91** [comment]
The cuda errors seem to be all gone.  nvidia-smi shows activity and processes on the card.  I do see errors now with darknet. 
I see motion being detected but the nvr is not being called to record.  I could be my config though. I used the example in #306  to get a running config.  

Darknet Errors - only happens once on startup. 
`Traceback (most recent call last):

  File "/src/viseron/components/__init__.py", line 130, in setup_component

    result = component_module.setup(self._vis, config)

  File "/src/viseron/components/darknet/__init__.py", line 99, in setup

    vis.data[COMPONENT] = DarknetNative(vis, config[CONFIG_OBJECT_DETECTOR])

  File "/src/viseron/components/darknet/__init__.py", line 284, in __init__

    raise LoadDarknetError("Failed to load Darknet network in child process")

viseron.components.darknet.LoadDarknetError: Failed to load Darknet network in child process

[2022-04-12 08:09:28] [ERROR   ] [viseron.components] - Uncaught exception setting up component darknet: Failed to load Darknet network in child process

None

[2022-04-12 08:09:28] [ERROR   ] [viseron.components] - Failed setup of component darknet`

**Comment by roflcoopter** [comment]
Can you turn on debug logging and restart?
Might give an indication to why darknet does not load 

```yaml 
logger: 
  default_level: debug 
```

**Comment by roflcoopter** [comment]
Hmm strange.

The native Darknet implementation is kind of bad at reporting errors sadly, not much i can do about that.

I checked and its build with:
```
nvcc -gencode arch=compute_35,code=sm_35 -gencode arch=compute_50,code=[sm_50,compute_50] -gencode arch=compute_52,code=[sm_52,compute_52] -gencode arch=compute_61,code=[sm_61,compute_61]
```

which means that your GPUs architecture is supported.
I really have no idea what culd be wrong.

My plan is to implement pytorch at some point but i have not had the time yet

**Comment by roflcoopter** [comment]
CUDA in the container is 11.4.1, could you maybe try a downgrade?

**Comment by bailboy91** [comment]
I downgraded all the way to down to cuda 10.1 on the host and it appears to be working correctly.  Lots of debug messages about confidence in identifying trucks, cars, birds, ect.  in the docker compose file i did have to include `- NVIDIA_DISABLE_REQUIRE=1` as an environmental variable to get the container to start. Checking out the recordings i can see jpeg images of a truck identified.  Motion was triggered and the nvr recorded an mp4 as well.  oddly nvidia-smi doesn't show any services for viseron on the host or container though but all seems to be working.  Thank you for your help and time!

**Comment by bailboy91** [comment]
Reopening due to some testing over the past few days.  I realized that even though i had no cuda errors that the k620 was not being utilized for object detection.  I completely removed all cuda and nvidia drivers and started fresh with cuda 11-6 and driver 510 on the host.  I compiled opencv and darknet and ran some tests using yolov3 and yolov4.  Both work against the test images and i see gpu utilization and memory consumption.  However for my gpu with 2gigs of vram i had to edit the configs to 416 for height and width to complete the object detection.  
I used opencv 4.5.0 and the latest darknet.  I used the generic Makefile for darknet setting gpu=1 and opencv=1.  

I cannot quite figure out just yet how to manually build the container locally to try different build flags for darknet / opencv.  

the container still gets the same error as the original issue. same lines and everything.  

Do you have any advice for testing in the container? How can i manually desk darknet in the container against some static images?

**Comment by roflcoopter** [comment]
Strange, can you try and see if you can get any other Docker containers that run Darknet to work?
Eg https://github.com/daisukekobayashi/darknet-docker
Just to narrow down the scope a little.

If you want to exec into the Viseron container you can run it like this:
```docker run -it --rm --entrypoint="" --runtime=nvidia roflcoopter/amd64-cuda-viseron:modularize bash```

From there on you can run any command you like.  The Darknet library is located in `/usr/local/lib`

You could also build the Dockerfile.darknet and test it there if you want, but you need to comment out line 65-68 since that cleans up the image and only stores the libraries.
The command to build that image is:
```docker-compose --file ./azure-pipelines/docker-compose-build.yaml --env ./azure-pipelines/.env build amd64-cuda-darknet```

Let me know if you need any assistance

**Comment by bailboy91** [comment]
I've been able to test the above linked container and it does work with my gpu. nvidia-smi shows the container darknet process start and i see load with the expected output.  I will test with the viseron container later today as time permits.  

Thank you for the guidance in troubleshooting!

**Comment by bailboy91** [comment]
I used the compose command string you provided and it built successfully but that is as far as i had gotten. I am not sure how to test it once it is built.  I am still quite new to building containers.  I was successful however with the the other container test you linked. It worked just fine.  

I did do some cross checking and the only build difference i can tell between my darknet tests and the viseron darknet is that i did not setup cudnn.  I believe that is the same with the container test you linked.  This is as far as i have been able to get this week so far on the issue.

**Comment by roflcoopter** [comment]
Did you comment out line 65-68 in `docker/amd64-cuda/Dockerfile.darknet` before building?

If so you can exec into the container and run the tests from the darknet repo, like this:
`docker run -it --rm --runtime=nvidia roflcoopter/amd64-cuda-darknet:8a0bf84c bash`

When you are inside the container you can run this command to download the weights and test Darknet:
```
apt-get install -y --no-install-recommends wget && \
cd /tmp/darknet && \
wget https://github.com/AlexeyAB/darknet/releases/download/darknet_yolo_v3_optimal/yolov4.weights && \
./darknet detect cfg/yolov4.cfg yolov4.weights data/dog.jpg
```

**Comment by roflcoopter** [comment]
You could try to remove line 47 and line 48 and rebuild the container to see if that is causing issues (disables AVX and OpenMP support)

**Comment by bailboy91** [comment]
commenting out lines 47 and 48 seems to have done it!  I ran it again monitoring gpu usage and it does in fact utilize the GPU with lines 47 and 48 commented out.

**Comment by roflcoopter** [comment]
Great! Dont really need AVX anyway since the CPU version of Viseron uses OpenCV instead for Darknet support.

I will remove it and push new builds tomorrow.
Thanks for running tests for me!

**Comment by bailboy91** [comment]
Once it's up I'll pull it in and test it out!

**Comment by roflcoopter** [comment]
The changes are now pushed, let me know if it works for you

**Comment by bailboy91** [comment]
I pulled in the latest and it is running without error! I can see utilization in nvtop for the darknet process in the container.  It is yet to record anything or take a snapshot but I believe that to be some of my settings in the config.  All seems to be functioning now though! I am going to close this one out for good! Thank you for your help, I absolutely love this project.

**Comment by roflcoopter** [comment]
Awesome!
