### ISSUE TITLE
Issue getting static mjpeg to work

### ISSUE THREAD

**Issue by russellevans** [roflcoopter/viseron#342]
Thank you for all your work on this product.....it is totally fantastic.  I have not done it before but I figure out how to  "buy you a coffee".

The documentation is great but there is one thing that I have not been able to figure out.

Below are the error and the config file.

Thanks for any help you can give

![image](https://user-images.githubusercontent.com/78644515/164641531-d7f61e0c-88a3-4cd9-83bf-ebdd18be5f67.png)

`  - name: Camera-1
    host: 192.168.1.21
    port: 554
    username: admin
    password: Facereader
    path: /Streaming/Channels/102/
    codec: h264
    width: 640
    height: 480
    fps: 6
    static_mjpeg_streams:
      my-big-front-door-stream:
        width: 1920
        height: 1080
        draw_objects: True
      stream1:
        width: 100
        height: 100
        draw_objects: True
    logging:
      level: debug
`

**Comment by russellevans** [comment]
I found out that change the Camera name to remove "-" fixed the issue.

**Comment by roflcoopter** [comment]
Glad you figured it out!

And thanks a lot for the donation :)
