### ISSUE TITLE
Documentation - How to get the camera slugs

### ISSUE THREAD

**Issue by tttdevelop** [roflcoopter/viseron#345]
In the chapter Dynamic MJPEG Streams, it mentions how to find your camera slugs via a docker exec command. This is not not working. It comes up with the error;

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: cannot import name 'CONFIG' from 'viseron.config' (/src/viseron/config/__init__.py)

```

The correct docker exec command is this;

`docker exec -it viseron python3 -c "from viseron.config import load_config; from viseron.helpers import print_slugs; print_slugs(load_config());"`

**Comment by roflcoopter** [comment]
Thanks! Will make sure to fix it as part of #306

**Comment by gniknalu** [comment]
> In the chapter Dynamic MJPEG Streams, it mentions how to find your camera slugs via a docker exec command. This is not not working. It comes up with the error;


To satisfy my own curiosity, what is a camera slug?

(apologies for messing up the thread)

**Comment by roflcoopter** [comment]
This is no longer an issue in v2 since you specify the slugs yourself
