### ISSUE TITLE
Modularize: Use only valid path characters for recorder

### ISSUE THREAD

**Issue by luigi311** [roflcoopter/viseron#351]
Use only valid path characters for the recorder. Testing with the modularize tags the recorder seems to be using the timestamp directly for the names so 01:39:38.mp4 which while is informative it is not a valid windows path so the windows explorer just returns nonsense. I would recommend replacing : with _ or something to that effect that way there is still a separator and paths for windows will be valid.

**Comment by roflcoopter** [comment]
Great!
You are right, the documentation is not quite done yet, I am working on it tho.
Moving towards a little more advanced setup than just a huge README file so it's taking some time
