### ISSUE TITLE
Post Processor - LPR

### ISSUE THREAD

**Issue by shmrymbd** [roflcoopter/viseron#365]
New feature for LPR / ALPR would be good.

**Comment by roflcoopter** [comment]
Great idea! I have been thinking about it for a while, will add it soon.

**Comment by roflcoopter** [comment]
@shmrymbd Do you have any good ALPR solution that you have used in the past?
Most i can find are paid and i would like to find a free alternative

**Comment by paulblakely** [comment]
I also have some interest in LPR, and ran across OpenALPR. It looks like they're trying to sell it as a service, but also have the source available at https://github.com/openalpr/openalpr -- could this work?

**Comment by roflcoopter** [comment]
Not sure, it states here that you need a license to use it: https://pypi.org/project/openalpr/

**Comment by paulblakely** [comment]
I was able to download the latest windows release (ubuntu is also supported) from https://github.com/openalpr/openalpr/releases and just run it on sample files.

![Screenshot 2022-11-28 092748](https://user-images.githubusercontent.com/2105970/204316369-face3506-ceb8-41f7-bfd3-6ba872411cae.jpg)

Perhaps that pypi wrapper only supports the commercial version? From the quick readme example, I don't see where you would configure where the OpenALPR server is running. Perhaps it's set up to use the paid cloud service.

**Comment by roflcoopter** [comment]
Sorry this has taken so much time but this is finally in the `dev` branch!

It is implemented by the new CodeProject.AI component and you can find the docs [here](https://dev--viseron.netlify.app/components-explorer/components/codeprojectai)
