### ISSUE TITLE
Error starting decoder pipe! mp3float Header missing

### ISSUE THREAD

**Issue by pixeye33** [roflcoopter/viseron#37]
Hello,

I've just started playing with this, and i'm having an issue i don't know how to fix... And i'm sure this would also help others in the future 👍 

With docker image viseron :
```
[lib.nvr.salon           ] [DEBUG   ] - NVR thread initialized
[lib.nvr.salon           ] [DEBUG   ] - Waiting for first frame
[root                    ] [INFO    ] - Initialization complete
[lib.camera.salon        ] [ERROR   ] - Error starting decoder pipe! [mp3 @ 0x55838c023740] Header missing

[lib.camera.salon        ] [ERROR   ] - Error starting decoder pipe! [mp3 @ 0x562193204740] Header missing

[lib.camera.salon        ] [ERROR   ] - Error starting decoder pipe! [mp3 @ 0x55ae76efd740] Header missing

[lib.camera.salon        ] [ERROR   ] - Error starting decoder pipe! [mp3 @ 0x562dc7756740] Header missing

[lib.camera.salon        ] [INFO    ] - Succesful reconnection!
[lib.camera.salon        ] [DEBUG   ] - Running object detection at 1s interval, every 25 frame(s)
[lib.camera.salon        ] [DEBUG   ] - Running motion detection at 1s interval, every 25 frame(s)
[lib.nvr.salon           ] [DEBUG   ] - First frame received
```

With docker image viseron-vaapi :
```
[lib.nvr.salon           ] [DEBUG   ] - NVR thread initialized
[lib.nvr.salon           ] [DEBUG   ] - Waiting for first frame
[root                    ] [INFO    ] - Initialization complete
[lib.camera.salon        ] [ERROR   ] - Error starting decoder pipe! [mp3float @ 0x561b137d2d00] Header missing

[lib.camera.salon        ] [ERROR   ] - Error starting decoder pipe! [mp3float @ 0x55f7ed259d00] Header missing
```

using vaapi, it endlesly says the last line and never actually starts.
Also, i've noticed that the decoder is mp3float instead of mp3.

After some googling i've found the option `-c:a mp3` but i'm not sure where to put it (in viseron config), or that it would help.

As a debug step i've attempted this, and with or without the mp3 codec specified i get mostly the same result (replace mp3 with mp3float)
```
docker exec -it prod_viseron_1 ffmpeg -hide_banner -avoid_negative_ts make_zero -fflags nobuffer -flags low_delay -strict experimental -fflags +genpts -stimeout 5000000 -use_wallclock_as_timestamps 1 -vsync 0 -hwaccel vaapi -vaapi_device /dev/dri/renderD128 -rtsp_transport tcp -c:a mp3 -i rtsp://root:ismart12@10.8.0.250:8554/unicast -f null /dev/null
[mp3 @ 0x5622b4438c40] Header missing
Input #0, rtsp, from 'rtsp://root:ismart12@10.8.0.250:8554/unicast':
  Metadata:
    title           : LIVE555 Streaming Media v2020.03.06
    comment         : LIVE555 Streaming Media v2020.03.06
  Duration: N/A, start: 1600894569.567244, bitrate: N/A
    Stream #0:0: Video: h264 (Main), yuv420p(progressive), 1280x720, 25 fps, 25 tbr, 90k tbn, 50 tbc
    Stream #0:1: Audio: mp3, 44100 Hz, mono, s16p, 64 kb/s
Stream mapping:
  Stream #0:0 -> #0:0 (h264 (native) -> wrapped_avframe (native))
  Stream #0:1 -> #0:1 (mp3 (native) -> pcm_s16le (native))
Press [q] to stop, [?] for help
Too many packets buffered for output stream 0:1.32:22.77 bitrate=N/A speed=N/A    
Conversion failed!
```

Additional info : i have a i3-7100T CPU with /dev/dri/renderD128 existing and /dev/dri mounted as a device trough docker.

i can't pinpoint what's wrong in my setup...
Can you help me ? 👍 
Thanks !

**Comment by roflcoopter** [comment]
Ah interesting, I never worked with audio decoder before, i am guessing this could become an issue even if you manage to get the decoder to work.

I am gonna see if i can find an online RTSP stream with audio to test with. Ill get back to you shortly

**Comment by roflcoopter** [comment]
In the meantime, can you try adding
```yaml
input_args:
  - -an
``` 
to your camera config? That should skip the audio completely

**Comment by pixeye33** [comment]
Hello,
thanks for your quick response !

Before any changes : I've let it run and the behaviour ended up to be the same at the very first log i've shared (but after a much longer time).

I've just tried the config suggested :
`[lib.camera.salon        ] [DEBUG   ] - FFMPEG decoder command: ffmpeg -hide_banner -loglevel panic -an -hwaccel vaapi -vaapi_device /dev/dri/renderD128 -rtsp_transport tcp -i rtsp://root:ismart12@10.8.0.250:8554/unicast -f rawvideo -pix_fmt nv12 pipe:1`

but i'm still getting the same message : 
`[lib.camera.salon        ] [ERROR   ] - Error starting decoder pipe! [mp3float @ 0x55dcc64b2600] Header missing`
and after some time it seems to start working (i did not configured the recording yet to look at the videos captured).

**Comment by roflcoopter** [comment]
Okay i see. To make it easier for the user to debug, Viseron will first try to open the stream with ```-loglevel error``` and check for any errors. However, it seems not all of these errors are fatal, and the stream may continue anyway. 

I will add a config option so you can supply your own recoverable errors which Viseron will then ignore and let the decoder start. Hold tight!

**Comment by pixeye33** [comment]
I was able to make the issue disapear by playing with the settings on the camera, but yes i do think those improvements will help to understand what's happening 👍

**Comment by roflcoopter** [comment]
great to hear!
