### ISSUE TITLE
object_detection + MQTT - Expose number of detected objects

### ISSUE THREAD

**Issue by paulblakely** [roflcoopter/viseron#39]
First of all, thanks for all the excellent work on Viseron, it works impressively well with CUDA.

The binary sensors in Home Assistant showing if a `person` `car` etc was detected are great, but it would be better if they could report a count of how many of that object is detected.

For my usecase, I want to be notified when a car enters my driveway, but also want to be notified if a second car enters (assuming the first car is parked for hours).

Would it be possible to expose counts of each identified label?

**Comment by roflcoopter** [comment]
Great to hear you're liking Viseron!

Seems quite obvious now that you mention it, I will try to squeeze it in to the next release, should be fairly easy. I'll expose the count as an attribute.

I am working on face recognition right now so it might take a few days. License plate recognition will come soon aswell which I guess would fit your use case quite well.

**Comment by roflcoopter** [comment]
This is now available in the current beta
