### ISSUE TITLE
what am i doing wrong

### ISSUE THREAD

**Issue by loordgek** [roflcoopter/viseron#394]
hello i am trying to setup viseron using
`sudo docker run --rm \
  -v {recordings path}:/recordings \
  -v {config path}:/config \
  -v /etc/localtime:/etc/localtime:ro \
  -p 8888:8888 \
  --name viseron \
  roflcoopter/viseron:latest`
but i am getting 
`docker: invalid reference format.
See 'docker run --help'.`
i have no experience w/ docker
i use this https://viseron.netlify.app/docs/documentation/installation

**Comment by roflcoopter** [comment]
Hello!

Should be working, but i suggest you try this instead:
```
sudo docker run --rm -v {recordings path}:/recordings -v {config path}:/config -v /etc/localtime:/etc/localtime:ro -p 8888:8888 --name viseron roflcoopter/viseron:2.0.0b3
```

You need to change `{recordings path}` and `{config path}` to point to a folder on your machine as well

**Comment by loordgek** [comment]
thanks i got that working 
i am now getting https://gist.github.com/loordgek/fc5d81e699e44c6d47fdf9d619157402

**Comment by roflcoopter** [comment]
That's a regression, sorry about that. Will fix later today!

It shouldn't stop you from editing the config tho, that error will go away when you have configured atleast one camera

**Comment by loordgek** [comment]
it is running now 
https://gist.github.com/loordgek/d4f600dab45cbefc74d4ecb27d06cdc6

how do you get to the web UI
https://172.17.0.2:8888 < that does not work in firefox

**Comment by roflcoopter** [comment]
https://172.17.0.2:8888/ points to the IP of your Docker container.
You need to navigate to the IP of your Docker host instead: `http://<your_docker_host_here>:8888/`

**Comment by roflcoopter** [comment]
Closing as resolved
