### ISSUE TITLE
[FR] - Zoning

### ISSUE THREAD

**Issue by jaburges** [roflcoopter/viseron#4]
Based on cameras 'view' it would be great (probably when you get to the UI) to be able to create zones on the camera image. This way you can exclude certain areas or dial in sensitivity in others

**Comment by roflcoopter** [comment]
I will implement this feature next, several people have requested/asked for it

**Comment by roflcoopter** [comment]
closed in [v1.4.0](https://github.com/roflcoopter/viseron/releases/tag/v1.4.0)
