### ISSUE TITLE
[Viseron2] Regression in MQTT data delivered

### ISSUE THREAD

**Issue by paulblakely** [roflcoopter/viseron#401]
I noticed a change from Viseron to Viseron2 in the MQTT data being sent.

For context, I have a home assistant automation to alert me if there's something new in the driveway. In Viseron1, I am able to count the items at `viseron/driveway/binary_sensor/object_detected` in the `attributes.objects` field. When this goes from 0 to 1, or 1 to 2, etc, Home assistant iterates through the list to tell me "Car and person detected in the driveway."

In Viseron2, `viseron2/binary_sensor/driveway_object_detected` always has an empty `attributes` object.

Is it possible for me to still use this automation as is, and if not, would it be possible to add the detected objects to the attributes of the viseron2 message?

Thanks!

| Viseron1 | Viseron2 |
| ----------- | ----------- |
| <img width="1019" alt="Screenshot 2022-11-26 at 11 58 09 AM" src="https://user-images.githubusercontent.com/2105970/204102775-0b052de4-a180-4c17-a05c-46a28d4b063c.png"> | <img width="1019" alt="Screenshot 2022-11-26 at 11 56 58 AM" src="https://user-images.githubusercontent.com/2105970/204102773-8bc2c173-0626-4bb5-8d22-4db4d2e7fc4f.png"> |

**Comment by roflcoopter** [comment]
Sorry about that, will add it back!

**Comment by paulblakely** [comment]
This is working great, thanks!

**Comment by roflcoopter** [comment]
Great!
