### ISSUE TITLE
No HW Acceleration on Intel Nuc

### ISSUE THREAD

**Issue by tfriedlx** [roflcoopter/viseron#408]
I have a Intel NUC11ATKC4 (https://www.intel.com/content/www/us/en/products/sku/217669/intel-nuc-11-essential-kit-nuc11atkc4/specifications.html) which has a Intel® Celeron® Processor N5105 (4M Cache, up to 2.90 GHz) with Intel® UHD Graphics.

I installed the VAAPI driver on my Ubuntu installation and also pass it along in docker-compose via 

```
devices:
  - /dev/dri 
```

However when starting it says VA-API cannot be used.

For frigate hardware acceleration worked via **-c:v h264_v4l2m2m** - is there a way to use this? Or does it have to be VAAPI?

**Comment by roflcoopter** [comment]
If you exec into the container, what is the output of the command `vainfo`?

**Comment by tfriedlx** [comment]
`error: XDG_RUNTIME_DIR not set in the environment.
error: can't connect to X server!
libva info: VA-API version 1.7.0
libva info: User environment variable requested driver 'i965'
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/i965_drv_video.so
libva info: Found init function __vaDriverInit_1_6
libva error: /usr/lib/x86_64-linux-gnu/dri/i965_drv_video.so init failed
libva info: va_openDriver() returns -1
vaInitialize failed with error code -1 (unknown libva error),exit`

On the host I get:
`error: XDG_RUNTIME_DIR is invalid or not set in the environment.
error: can't connect to X server!
libva info: VA-API version 1.15.0
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_14
libva info: va_openDriver() returns 0
vainfo: VA-API version: 1.15 (libva 2.12.0)
vainfo: Driver version: Intel iHD driver for Intel(R) Gen Graphics - 22.4.3 ()
vainfo: Supported profile and entrypoints
      VAProfileNone                   :	VAEntrypointVideoProc
      VAProfileNone                   :	VAEntrypointStats
      VAProfileMPEG2Simple            :	VAEntrypointVLD
      VAProfileMPEG2Main              :	VAEntrypointVLD
      VAProfileH264Main               :	VAEntrypointVLD
      VAProfileH264Main               :	VAEntrypointEncSliceLP
      VAProfileH264High               :	VAEntrypointVLD
      VAProfileH264High               :	VAEntrypointEncSliceLP
      VAProfileJPEGBaseline           :	VAEntrypointVLD
      VAProfileJPEGBaseline           :	VAEntrypointEncPicture
      VAProfileH264ConstrainedBaseline:	VAEntrypointVLD
      VAProfileH264ConstrainedBaseline:	VAEntrypointEncSliceLP
      VAProfileVP8Version0_3          :	VAEntrypointVLD
      VAProfileHEVCMain               :	VAEntrypointVLD
      VAProfileHEVCMain               :	VAEntrypointEncSliceLP
      VAProfileHEVCMain10             :	VAEntrypointVLD
      VAProfileHEVCMain10             :	VAEntrypointEncSliceLP
      VAProfileVP9Profile0            :	VAEntrypointVLD
      VAProfileVP9Profile1            :	VAEntrypointVLD
      VAProfileVP9Profile2            :	VAEntrypointVLD
      VAProfileVP9Profile3            :	VAEntrypointVLD
      VAProfileHEVCMain422_10         :	VAEntrypointVLD
      VAProfileHEVCMain444            :	VAEntrypointVLD
      VAProfileHEVCMain444            :	VAEntrypointEncSliceLP
      VAProfileHEVCMain444_10         :	VAEntrypointVLD
      VAProfileHEVCMain444_10         :	VAEntrypointEncSliceLP`

On startup I get:
`****** Checking for hardware acceleration platforms ******
OpenCL is available!
VA-API cannot be used
CUDA cannot be used
*********************** Done *****************************`

**Comment by tfriedlx** [comment]
Just to add on that: I had to install intel-media-va-driver to get it working on the host - before I had the same output as in the container.

**Comment by roflcoopter** [comment]
Okay, and if you run `apt-get update && apt-get install --no-install-recommends -y intel-media-va-driver` inside the container, does `vainfo` work then?

**Comment by tfriedlx** [comment]
Still the same

`error: XDG_RUNTIME_DIR not set in the environment.
error: can't connect to X server!
libva info: VA-API version 1.7.0
libva info: User environment variable requested driver 'i965'
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/i965_drv_video.so
libva info: Found init function __vaDriverInit_1_6
libva error: /usr/lib/x86_64-linux-gnu/dri/i965_drv_video.so init failed
libva info: va_openDriver() returns -1
vaInitialize failed with error code -1 (unknown libva error),exit`

Also it's still referncing /usr/lib/x86_64-linux-gnu/dri/i965_drv_video.so instead of /usr/lib/x86_64-linux-gnu/dri/iHD_drv_video.so

After I set **LIBVA_DRIVER_NAME=iHD** before calling vainfo it works:

`error: XDG_RUNTIME_DIR not set in the environment.
error: can't connect to X server!
libva info: VA-API version 1.7.0
libva info: User environment variable requested driver 'iHD'
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_7
libva info: va_openDriver() returns 0
vainfo: VA-API version: 1.7 (libva 2.6.0)
vainfo: Driver version: Intel iHD driver for Intel(R) Gen Graphics - 20.1.1 ()
vainfo: Supported profile and entrypoints
      VAProfileNone                   :	VAEntrypointVideoProc
      VAProfileNone                   :	VAEntrypointStats
      VAProfileMPEG2Simple            :	VAEntrypointVLD
      VAProfileMPEG2Main              :	VAEntrypointVLD
      VAProfileH264Main               :	VAEntrypointVLD
      VAProfileH264Main               :	VAEntrypointEncSliceLP
      VAProfileH264High               :	VAEntrypointVLD
      VAProfileH264High               :	VAEntrypointEncSliceLP
      VAProfileJPEGBaseline           :	VAEntrypointVLD
      VAProfileJPEGBaseline           :	VAEntrypointEncPicture
      VAProfileH264ConstrainedBaseline:	VAEntrypointVLD
      VAProfileH264ConstrainedBaseline:	VAEntrypointEncSliceLP
      VAProfileVP8Version0_3          :	VAEntrypointVLD
      VAProfileHEVCMain               :	VAEntrypointVLD
      VAProfileHEVCMain               :	VAEntrypointEncSliceLP
      VAProfileHEVCMain10             :	VAEntrypointVLD
      VAProfileHEVCMain10             :	VAEntrypointEncSliceLP
      VAProfileVP9Profile0            :	VAEntrypointVLD
      VAProfileVP9Profile1            :	VAEntrypointVLD
      VAProfileVP9Profile2            :	VAEntrypointVLD
      VAProfileVP9Profile3            :	VAEntrypointVLD
      VAProfileHEVCMain422_10         :	VAEntrypointVLD
      VAProfileHEVCMain444            :	VAEntrypointVLD
      VAProfileHEVCMain444            :	VAEntrypointEncSliceLP
      VAProfileHEVCMain444_10         :	VAEntrypointVLD
      VAProfileHEVCMain444_10         :	VAEntrypointEncSliceLP`

**Comment by roflcoopter** [comment]
Yeah i suspected that LIBVA_DRIVER_NAME could be the issue, my CPU supports both i965 and iHD, but it appears yours only supports iHD.

I will install those extra libraries and unset LIBVA_DRIVER_NAME so that its picked up automatically. Will let you know when the builds are complete

**Comment by roflcoopter** [comment]
if you run `intel_gpu_top` on the host, does it show any activity?

If you want to try another decoder you can set `codec: h264_v4l2m2m` and `hwaccel_args: []` and Viseron will use that instead of the default.

**Comment by tfriedlx** [comment]
Yes, intel_gpu_top shows around 26% usage of the GPU for video. Maybe I need to tweak my streams.

With frigate I had great CPU usage with **-c:v h264_qsv** for the hwaccel_args but I haven't managed to apply that to viseron yet - no matter how I try it says it doesn't recognize it.

**Comment by roflcoopter** [comment]
qsv decoders are now included in `dev` and `v2.0.0b4`

**Comment by tfriedlx** [comment]
Thanks! Any idea on how to use them? I tried 

codec: h264_qsv
hwaccel_args: qsv 

but without any luck so far.

**Comment by roflcoopter** [comment]
Setting `codec: h264_qsv` and `hwaccel_args: []` should be enough.

If you are using a substream you need to set the same parameters there
