### ISSUE TITLE
compreface similarity vs unknown

### ISSUE THREAD

**Issue by gofaster** [roflcoopter/viseron#411]
Compreface face recognition seems to return a best match for any face, along with a similarity (confidence) attribute.   Consequently a new unknown face is never saved even if `save_unknown_faces: true`
Perhaps a new `similarity_threshold` can be introduced such that any value less than that is considered and saved as unknown?

[https://github.com/exadel-inc/CompreFace/blob/master/docs/Face-services-and-plugins.md#face-recognition](url)

**Comment by roflcoopter** [comment]
Yes makes total sense!

You are firing off great ideas faster than i can develop 😂

**Comment by roflcoopter** [comment]
Closed in #412
