### ISSUE TITLE
[Feature Request] Object detection label boxes

### ISSUE THREAD

**Issue by ConstBur** [roflcoopter/viseron#426]
Hey @roflcoopter, keep up the great work, v2 is running great :)

I'm using DarkNet for object detection, and I'd like to have a URL/config option that creates a snapshot from the camera containing label boxes around detected objects, kind of like this:
![image](https://user-images.githubusercontent.com/29761079/208217098-4ff04cf5-3fff-4257-b2f2-034b187f6b85.png)
(image taken from https://github.com/WongKinYiu/yolov7#instance-segmentation)

If there already is a way to do this, please let me know :)

**Comment by roflcoopter** [comment]
When a recording starts, Viseron creates a thumbnail with the objects drawn much like your image.
It is stored next to the recording with the same name but with `.jpg` extension.

If you want to do it on demand you can check out the [MJPEG streams](https://viseron.netlify.app/components-explorer/components/ffmpeg#mjpeg-streams) and use the `draw_objects` option.
