### ISSUE TITLE
[Regression V2] Doubled camera name in recording URLs 

### ISSUE THREAD

**Issue by ConstBur** [roflcoopter/viseron#427]
The URLs of the recordings in the frontend contain /camera_name twice, e.g. /recordings/garage/garage/2022-12-14/2022-12-14_22:10:48.mp4.

I'd guess the problem is here: https://github.com/roflcoopter/viseron/blob/dev/frontend/src/components/videoplayer/VideoPlayer.tsx#L56

If you'd like to make a quick and dirty fix on the frontend side, you could pass the camera name to the component and do something like this:
```js
content: recording.filename.split(".")[0].replace(`/${camera_name}`, "")
```

**Comment by roflcoopter** [comment]
Thanks for the report!

However, i am not seeing this issue, could you explain a bit more where this occurs?
If i copy the link from a recording and open it directly in the browser it looks like this:
`https://my_domain.com/recordings/doorbell/2022-12-17/12:55:12.mov`

**Comment by ConstBur** [comment]
Figured out why it happens: in my recorder config I put the folder as ```/recordings/garage``` and didn't realize Viseron was appending the camera name. I guess it would be a nice addition to the docs :)
