### ISSUE TITLE
[FEATURE] additional recording options/presentation

### ISSUE THREAD

**Issue by spupuz** [roflcoopter/viseron#441]
- [X] Separate view of recorded captures per camera and per day 
- [X] Add an option to define how long a recorded will last in storage and when will be deleted
- [x] Add an option on GUI to delete each single video capture and eventually the ability to delete a whole day of captures

**Comment by jamitupya** [comment]
I think point number 2 is already available, check out the ffmpeg component doco for the camera configuration:) 
Seems to work for me.

Point 3 I absolutely agree with. I’ve recently had to go manually digging a file system cause someone did something stupid and it needed a good purge.

**Comment by roflcoopter** [comment]
Point 1 is now in v2.1.0
Point 2 can be achieved already with `retention` as @jamitupya pointed out
Will work on point 3 soon!

**Comment by spupuz** [comment]
wait for other feature thanks for the tips!! :) first page login is really needed!!

**Comment by roflcoopter** [comment]
Indeed, will probably focus on that for 2.2. 
It's quite complex to manage users and authentication so I need to do some proper research before I start development

**Comment by roflcoopter** [comment]
Closed in #459 

It is currently in the `dev` tag if you want to try it out.

**Comment by spupuz** [comment]
![image](https://user-images.githubusercontent.com/1721792/213201457-c1f22eaf-e0eb-4f33-8924-b320d5a117e0.png)

a view similar to this would be more clear IMHO.

also the ability to see one video at time and once it as played the video it passes to play directly to the next one

![image](https://user-images.githubusercontent.com/1721792/213201841-5eca13e2-35e6-4218-9fd3-df64e03fa677.png)
