### ISSUE TITLE
[FR] Support for torchvision

### ISSUE THREAD

**Issue by sdwilsh** [roflcoopter/viseron#45]
Would you be interested in supporting [torchvision](https://github.com/pytorch/vision/) as an object detector as well?

**Comment by roflcoopter** [comment]
Definitely!

Seems easy enough to implement. Do you know if there are any pre trained models or do you have to train your own?

**Comment by sdwilsh** [comment]
There are a lot of [models](https://pytorch.org/docs/stable/torchvision/datasets.html) that can be downloaded.

**Comment by roflcoopter** [comment]
@sdwilsh Is this still of interest for you?

**Comment by sdwilsh** [comment]
Slightly, but mostly from an academic perspective (and to see what does best).  I wouldn't be upset if this got closed.

**Comment by roflcoopter** [comment]
I had a look at this a while back but could not get it to work in a good way, so i wont be implementing this. Sorry for the inconvenience
