### ISSUE TITLE
[FEATURE] Linked Cameras and Zones

### ISSUE THREAD

**Issue by jamitupya** [roflcoopter/viseron#450]
Would be helpful to link or group cameras for triggering of recording. ATM I use this type of feature  to record all cameras if a fire is detected. 

I’d like to improve further on this by being able to link zones and record zones specifically. 

The grouping of cameras I think is more important, but being able to see that a zone had an “event” happen in HA might be useful for others as well.

**Comment by roflcoopter** [comment]
Just to clarify, you would like to link cameras together, so when one starts recording, another one will record as well?

What do you mean by linking zones/record zones? 

> The grouping of cameras I think is more important, but being able to see that a zone had an “event” happen in HA might be useful for others as well.

Objects detected in zones are sent to Home Assistant using specific zone binary sensors. Or is there something else that you are after?

**Comment by jamitupya** [comment]
Actually found another thread about this so closing this :)
