### ISSUE TITLE
Recordings from missing camera not available in UI

### ISSUE THREAD

**Issue by bsyomov** [roflcoopter/viseron#466]
The recording page is not available for a camera that is configured, but from which there is no data stream at the moment.

IMHO, recordings UI must be completely decoupled from camera input availability and relay on config, not camera ffmpeg component state.
And on cameras page, configured, but unavailable cameras must be marked as unavailable, not just missed.

**Comment by mvicomoya** [comment]
I agree with @bsyomov here.

In addition to what he mentioned, if you restart the docker container while those cameras are unavailable they won't even show in the UI, and once they become available again, the system won't recover. The container must be restarted again.

**Comment by roflcoopter** [comment]
Will see what i can do about this after i finish off #469 

@mvicomoya Could you elaborate a bit on what you are saying here?
Viseron is meant to try and reconnect infinitely, but here might be something i have missed. Can you reproduce it easily? Is it as simple as turning off a camera during startup?

**Comment by mvicomoya** [comment]
Hey @roflcoopter,

Yes, pretty much as simple as that. While the cameras are offline, if I restart the container I get this backtrace and error:
```
[2023-01-25 20:30:35] [ERROR   ] [viseron.components] - Uncaught exception setting up domain camera for component ffmpeg: FFprobe could not connect to stream. Output: {'error': {'code': -1482175992, 'string': 'Server returned 5XX Server Error reply'}}, message repeated 2 times
viseron  | Traceback (most recent call last):
viseron  |   File "/src/viseron/components/__init__.py", line 384, in setup_domain
viseron  |     result = domain_module.setup(
viseron  |   File "/src/viseron/components/ffmpeg/camera.py", line 279, in setup
viseron  |     Camera(vis, config[identifier], identifier)
viseron  |   File "/src/viseron/components/ffmpeg/camera.py", line 302, in __init__
viseron  |     self.initialize_camera()
viseron  |   File "/src/viseron/components/ffmpeg/camera.py", line 322, in initialize_camera
viseron  |     self.stream = Stream(self._vis, self._config, self.identifier)
viseron  |   File "/src/viseron/components/ffmpeg/stream.py", line 117, in __init__
viseron  |     ) = self.get_stream_information(self.output_stream_url)
viseron  |   File "/src/viseron/components/ffmpeg/stream.py", line 348, in get_stream_information
viseron  |     width, height, fps, codec, audio_codec = self.ffprobe_stream_information(
viseron  |   File "/src/viseron/components/ffmpeg/stream.py", line 313, in ffprobe_stream_information
viseron  |     streams = self.run_ffprobe(stream_url)
viseron  |   File "/src/viseron/components/ffmpeg/stream.py", line 304, in run_ffprobe
viseron  |     raise FFprobeError(
viseron  | viseron.exceptions.FFprobeError: FFprobe could not connect to stream. Output: {'error': {'code': -1482175992, 'string': 'Server returned 5XX Server Error reply'}}
```

Then following that I a bunch other errors mentioning dependencies weren't able to be set up for object detector and motion domains (obviously).

Viseron initializes, but it never retries to set up these cameras again, so it never recovers unless I restart the container.

The result in the web UI is an infinite "Loading cameras" spinner for the cameras page, and a "Loading recordings" for the recordings page.


I think ideally we'd want Viseron to retry to set up these cameras later on, and for recordings to be available regardless (as long as the files are available).


By the way, I just want to take the opportunity to thank you for this app. It was so much easier to set up than Frigate for me, and works better for the cameras I'm using. Great work!!

**Comment by roflcoopter** [comment]
Got it, thanks for the detailed report.
The UI is quite fresh still, need to make it a bit better at displaying errors.
Can try to turn things around a little so that the camera can still be set up (and give access to recordings) but without the stream actually working.



> By the way, I just want to take the opportunity to thank you for this app. It was so much easier to set up than Frigate for me, and works better for the cameras I'm using. Great work!!

Thanks for the kind words!

**Comment by roflcoopter** [comment]
The proble

> Hey @roflcoopter,
> 
> Yes, pretty much as simple as that. While the cameras are offline, if I restart the container I get this backtrace and error:
> 
> ```
> [2023-01-25 20:30:35] [ERROR   ] [viseron.components] - Uncaught exception setting up domain camera for component ffmpeg: FFprobe could not connect to stream. Output: {'error': {'code': -1482175992, 'string': 'Server returned 5XX Server Error reply'}}, message repeated 2 times
> viseron  | Traceback (most recent call last):
> viseron  |   File "/src/viseron/components/__init__.py", line 384, in setup_domain
> viseron  |     result = domain_module.setup(
> viseron  |   File "/src/viseron/components/ffmpeg/camera.py", line 279, in setup
> viseron  |     Camera(vis, config[identifier], identifier)
> viseron  |   File "/src/viseron/components/ffmpeg/camera.py", line 302, in __init__
> viseron  |     self.initialize_camera()
> viseron  |   File "/src/viseron/components/ffmpeg/camera.py", line 322, in initialize_camera
> viseron  |     self.stream = Stream(self._vis, self._config, self.identifier)
> viseron  |   File "/src/viseron/components/ffmpeg/stream.py", line 117, in __init__
> viseron  |     ) = self.get_stream_information(self.output_stream_url)
> viseron  |   File "/src/viseron/components/ffmpeg/stream.py", line 348, in get_stream_information
> viseron  |     width, height, fps, codec, audio_codec = self.ffprobe_stream_information(
> viseron  |   File "/src/viseron/components/ffmpeg/stream.py", line 313, in ffprobe_stream_information
> viseron  |     streams = self.run_ffprobe(stream_url)
> viseron  |   File "/src/viseron/components/ffmpeg/stream.py", line 304, in run_ffprobe
> viseron  |     raise FFprobeError(
> viseron  | viseron.exceptions.FFprobeError: FFprobe could not connect to stream. Output: {'error': {'code': -1482175992, 'string': 'Server returned 5XX Server Error reply'}}
> ```
> 
> Then following that I see a bunch other errors mentioning dependencies weren't able to be set up for object detector and motion domains (obviously).
> 
> Viseron initializes, but it never retries to set up these cameras again, so it never recovers unless I restart the container.
> 
> The result in the web UI is an infinite "Loading cameras" spinner for the cameras page, and a "Loading recordings" for the recordings page.
> 
> I think ideally we'd want Viseron to retry to set up these cameras later on, and for recordings to be available regardless (as long as the files are available).
> 
> By the way, I just want to take the opportunity to thank you for this app. It was so much easier to set up than Frigate for me, and works better for the cameras I'm using. Great work!!

The FFprobe error is fixed now in `dev`, if a camera is unavailable when restarting Viseron, a retry will be attempted with a back-off system in place.

Regarding the original issue with recordings for missing cameras is actually a harder problem to solve than it might seem.
Everything is driven from a camera perspective and without a succesfully set up camera it makes it difficult to know what recordigns and parameters to use.

I will do some thinking on this and see if i can come up with a good solution

**Comment by roflcoopter** [comment]
![Failed_cameras](https://user-images.githubusercontent.com/26493864/229043080-2f4870d1-bd40-446b-b214-b1fedfe7691f.png)

This is a preview of what i have cooked up.
Failed cameras are marked with a red border and the error is displayed.

Cameras that are currently retrying setup is marked with an orange border.

Recordings for both the failed types of cameras are available as normal.
What do you think, is that good enough?

My next step to improve this is to show all kinds of errors, not just cameras, as well as viewing the logs in the UI, but that is for a future release

**Comment by mvicomoya** [comment]
That looks awesome! Pretty neat and way better that I would have anticipated. I would have been pleased enough with just the spinner, but this is so much better.

Great work! I just bought you a few coffees to give you a little bit of my support, given that I have close to zero time these days to contribute with my time.

**Comment by roflcoopter** [comment]
Thank you, much appreciated!

The `dev` builds are now complete so if you want to test it out its available.
I will be releasing a beta for the next release soon
