### ISSUE TITLE
[FR] Video in temp folder

### ISSUE THREAD

**Issue by TUISTERa** [roflcoopter/viseron#49]
Hello, i am using Viseron and i like it very much. I like that you make motion detection snapshot and video, but for me the video is unusable with automations. What i use is folder_watcher in Home assistant and when the video file is created automation is sending it to me. The problem is that the video that i get is still blank. I need to set waiting time for this, and to decide how long would be the record and wait to finish first and then i can send it to my phone. What i need and i think that it is good to have, is the video that is still recorded to be in some temp folder, and to be moved in the actual folder after the end of the record. I think that many dvr software use the temp way for safety measures...
Current situation:
/recordings/date/camera/actual_file.mp4 - zero bytes at the creation of the file and growing until the record end
What i mean in the FR:
/temp/current_record.mp4 -> /recordings/date/camera/actual_file.mp4 - with full size and ready to be sended, copied, downloaded or anything

**Comment by roflcoopter** [comment]
Great idea! Should be quite easy so you can expect it soon
