### ISSUE TITLE
Ability to stream Resized RTSP for home assistant

### ISSUE THREAD

**Issue by netpro25** [roflcoopter/viseron#497]
Viseron is awesome, it really fits the bill. I was looking for a step up from Ring but I wanted similar functionality and I think I'm pretty close to that using Viseron. Thanks so much for your hard work!

One thing that's not as straightforward as Ring though is the ability to view a camera on an echo device. I'm using Home Assistant Cloud (the subscription) to tie into my Alexa devices. When using the MJPEG camera integration pointing to Viseron I can't get the stream to show on the Echo. However, if add the integration for an RTSP camera viola it works. Seems to be a [common issue](https://community.home-assistant.io/t/alexa-camera-requirements-live-view-not-supported-on-this-device/389626/2). Here's my delima.

My cameras only allow 2 streams. I have the primary set to max resolution (4K) and the secondary to max which is 640x480. If I point the RTSP integration to the primary stream it does not work too well due to the bandwidth, however, using the secondary stream it works well except the quality and aspect ratio are not too good.

Idea! Is it possible to create substreams on Viseron similar to how MJPEG streams are created for RTSP? Could we have these exposed to Home Assistant through MQTT thus avoiding having to manually add the device? I believe it's possible with ffmpeg or is there a better way to do this?

**Comment by roflcoopter** [comment]
Thanks for the kind words!

The ability to re-stream a camera from Viseron is something I am planning to add soon, right now it cannot be done unfortunately

**Comment by netpro25** [comment]
Thank you!
