### ISSUE TITLE
Jetson Nano - GStreamer and FFmpeg error with Reolink cameras

### ISSUE THREAD

**Issue by JagerSprinkles** [roflcoopter/viseron#502]
I am trying to get my Reolink cameras working over rtsp or rtmp but have not been able to get GStreamer or FFmpeg to properly connect to the camera.

Both FFmpeg and GStreamer will not stream my Reolink cameras on the Jetson Nano. I spent a while debugging but don't have enough knowledge about FFmpeg or GStreamer to know what is happening here. The camera will stream fine in VLC on my desktop and through a few other programs I have tested including Viseron on my x86_64 Intel 11th Gen Nuc running Debian. FFmpeg will work on the Jetson if I force the codec to 'h264' in the config but then this is using the cpu to decode so is not optimal. Forcing this codec has no change with GStreamer.

FFmpeg outputs: "Did not receive a frame" then "Restarting frame pipe"
GStreamer outputs: 
```
ERROR: from element /GstPipeline:pipeline0/GstSplitMuxSink:mux/GstMP4Mux:mp4mux0: Could not multiplex stream.
Additional debug info:
gstqtmux.c(4561): gst_qt_mux_add_buffer (): /GstPipeline:pipeline0/GstSplitMuxSink:mux/GstMP4Mux:mp4mux0:
Buffer has no PTS.
GStreamer process has exited
```

These are just the last messages in the logs, I have included the full debug log for FFmpeg and the info log for GStreamer. I tried to get the debug logs for GStreamer but it output over 100MB in under a minute. I can grab this if it is needed.

When I run the FFmpeg command from the terminal it runs for a few seconds and then get a segmentation fault. If I modify the command and remove the "pipe:1" at the end it seems to work fine. I tried to remove it with output_args but then found those are only for the recorder settings so that didn't work.

Command used for testing. I got this from catching the command Viseron is running. Error output is attached.
```
ffmpeg_back_porch -hide_banner -loglevel info -avoid_negative_ts make_zero -fflags nobuffer -flags low_delay -strict experimental -fflags +genpts -use_wallclock_as_timestamps 1 -vsync 0 -stimeout 5000000 -c:v h264_nvv4l2dec -rtsp_transport tcp -i rtsp://user:pass@IPADDRESS:554/h264Preview_01_sub -f segment -segment_time 5 -reset_timestamps 1 -strftime 1 -c:v copy -c:a copy /tmp/back_porch/%Y%m%d%H%M%S.mp4 -vf fps=1.0 -f rawvideo -pix_fmt nv12 pipe:1
```

I have included logs for both GStreamer and FFmpeg. I am not sure exactly what additional info is needed but I can always provide more if required. I have tested things such as changing the password length, putting the user/pass in the url string, using rtmp, using main/sub stream from camera, a few different codecs, messing with /dev/dri permissions, and possibly some other things as I have been working on this on and off for a week or two.

[viseron gstreamer error from docker.txt](https://github.com/roflcoopter/viseron/files/10902949/viseron.gstreamer.error.from.docker.txt)
[viseron ffmpeg error from docker.txt](https://github.com/roflcoopter/viseron/files/10902950/viseron.ffmpeg.error.from.docker.txt)
[viseron ffmpeg error from terminal.txt](https://github.com/roflcoopter/viseron/files/10902951/viseron.ffmpeg.error.from.terminal.txt)
[config settings.txt](https://github.com/roflcoopter/viseron/files/10903228/config.settings.txt)

**Comment by JagerSprinkles** [comment]
Thank you for looking into this! I appreciate adding the option so I can test out how to get it to work. I will gladly report back and provide any logs or details that would be helpful since you said you don't have a Jetson.

**Comment by JagerSprinkles** [comment]
No need to rush on my behalf, I'll be here when it's ready.

**Comment by roflcoopter** [comment]
Sorry this took me longer than i had anticipated.

I have pushed a new update to `dev` which lets you set a `raw_pipeline`.
I dont really know what to change at this point tho.

Can you try increasing the `gstreamer_loglevel` and see if we get some more information?

**Comment by JagerSprinkles** [comment]
I can definitely get more detailed logs. Unfortunately this may have to wait a short time because I needed to return the cameras I had. The Wi-Fi was unstable so I need to pull cables and deploy the poe version of the cameras. I will report back with the logs and details once I get everything set up.

**Comment by JagerSprinkles** [comment]
I apologize for lack of updates on this. I have not been able to get time to redeploy my cameras. I do plan to come back to this once I have my new camera set up, will probably be a few more weeks though.

**Comment by JagerSprinkles** [comment]
I will not be able to troubleshoot this issue anymore. I have decided not to be using my Reolink cameras with the Jetson. This issue can be closed if you want.
