### ISSUE TITLE
add tcp input protocol for ffmpeg (and possibly gstreamer)

### ISSUE THREAD

**Issue by lolorc** [roflcoopter/viseron#519]
I'm using libcamera -o tcp:// to stream a camera off a raspberry pi

it's working ish with "protocol: http" but the start would be quicker with tcp://
I also have to set stream_format to rtmp and path: to /, both are useless in that case.

**Comment by roflcoopter** [comment]
Could you show an example of the working config so i better understand your issue?
What does the full URL look like? Is it just `tcp://<ip address>`?

**Comment by lolorc** [comment]
now useless since rtsp-simple-server/MediaMTX does support pi cam using libcamera.
