### ISSUE TITLE
Problem in deployment of viseron cointainer GPU

### ISSUE THREAD

**Issue by Davo-Exp4** [roflcoopter/viseron#537]
Hey guys I'm trying to deploy a docker container with GPU support, but i get this error: 

"docker: Error response from daemon: failed to create shim task: OCI runtime create failed: failed to create NVIDIA Container Runtime: failed to construct OCI spec modifier: failed to construct discoverer: failed to create Xorg discoverer: failed to locate libcuda.so: pattern libcuda.so.*.*.* not found: unknown."

I already export the evn variables where the libcudaso is located 

export LD_LIBRARY_PATH=/lib/x86_64-linux-gnu:$LD_LIBRARY_PATH

![image](https://user-images.githubusercontent.com/34872306/230271571-b769a5da-f321-436f-9025-1f5b940ec832.png)

and I succesfully installed nvidia-container toolkit 

sudo docker run --rm --runtime=nvidia --gpus all nvidia/cuda:11.6.2-base-ubuntu20.04 nvidia-smi

![image](https://user-images.githubusercontent.com/34872306/230271707-e642be89-ad61-44f1-a263-3832a2b30ae1.png)

I really appreciate any help. thank you

**Comment by k0stett** [comment]
Ubuntu 22.04. Just list of commands from my historyfile:
```
wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64/cuda-keyring_1.0-1_all.deb
sudo nano /etc/apt/sources.list.d/nvidia-container-toolkit.list
sudo nano /etc/apt/sources.list.d/nvidia-container-toolkit.list.distUpgrade 
sudo dpkg -i cuda-keyring_1.0-1_all.deb
sudo apt-key del 7fa2af80
sudo apt-get update
sudo apt autoremove nvidia* --purge
sudo apt autoremove libnvidia* --purge
distribution=$(. /etc/os-release;echo $ID$VERSION_ID) && curl -fsSL https://nvidia.github.io/libnvidia-container/gpgkey | sudo gpg --dearmor -o /usr/share/keyrings/nvidia-container-toolkit-keyring.gpg && curl -s -L https://nvidia.github.io/libnvidia-container/$distribution/libnvidia-container.list | sed 's#deb https://#deb [signed-by=/usr/share/keyrings/nvidia-container-toolkit-keyring.gpg] https://#g' | sudo tee /etc/apt/sources.list.d/nvidia-container-toolkit.list
# NEXT LINE NOT TO FORGET TO CORRECT YOUR UBUNTU VERSION in ANY CASES
sudo nano /etc/apt/sources.list.d/nvidia-container-toolkit.list 
sudo apt update
sudo apt-get install -y nvidia-container-toolkit
# Next line must be separate installation command
sudo apt install nvidia-driver-525-server
sudo nvidia-ctk runtime configure --runtime=docker
sudo reboot
nvidia-smi
sudo docker run --restart=always -dt -p 8888:8888/tcp -v /var/lib/videostorage/recordings:/recordings -v /etc/viseron:/config -v /etc/localtime:/etc/localtime:ro --tmpfs /tmp --name viseron --runtime=nvidia -e NVIDIA_VISIBLE_DEVICES=all -e NVIDIA_DRIVER_CAPABILITIES=compute,utility,video roflcoopter/amd64-cuda-viseron:latest
```

**Comment by roflcoopter** [comment]
Does the error occur while the container is starting or is it the Viseron python process that emits the error?

**Comment by sebastianvalle95** [comment]
I ran into the same issue while starting the Viseron container. What you have to do is update or download the latest drivers for your GPU. The 470.103.01 version you installed is from a year ago. For some reason, when you install the official drivers from the NVIDIA website, sometimes it doesn't pull the latest version.

Try installing the latest version, which is 470.182.03. Also, make sure you install the NVIDIA Container Toolkit and NVIDIA Docker 2 packages. Restart the Docker service, and then it should work.

**Comment by Davo-Exp4** [comment]
Thank you all of you guys, the problem was resolved using the recomendation on @sebastianvalle95
