### ISSUE TITLE
Adding support for cheap chinese cameras with non-standard RTSP

### ISSUE THREAD

**Issue by k0stett** [roflcoopter/viseron#538]
I've got a cheap chinese camera which sends incorrect data when connecting via RTSP, look here:
```
[rtsp @ 0x55a477850780] line='Transport: RTP/AVP;unicast;destination=10.0.0.9;source=10.0.0.125;client_port=7944-7945;server_port=6990-6991'
```
As a result, I've got an error:
```
[rtsp @ 0x562b13b9af00] Nonmatching transport in server reply
rtsp://admin:password@10.0.0.125:554/onvif1: Invalid data found when processing input
```
Found out peoples with similar fail on [StackOverflow](https://stackoverflow.com/questions/66280861/ffmpeg-nonmatching-transport-in-server-reply-but-openrtsp-works), so it will be more useful to integrate ffmpeg patch to your build of ffmpeg-nvenc in container amd64-cuda-viseron. Thanks.
P.S. Camera works ok in Restreamer but when I set it up as UDP.

**Comment by roflcoopter** [comment]
Id rather not do manual patches, it creates a lot of extra things to maintain.
Would be a lot better if it was implemented upstream!
