### ISSUE TITLE
Ignore Audio

### ISSUE THREAD

**Issue by beatles1** [roflcoopter/viseron#542]
Firstly this is great, exactly what I was looking for in a simple NVR.

Is there currently a way to ignore audio on the incoming stream? I don't want audio and it's in pcm_alaw anyway so can't be written to the mp4. Is there any way to just specify to drop the audio stream?

**Comment by roflcoopter** [comment]
Glad you like Viseron!

If you set `audio_codec: null` for the camera it should ignore the audio.

**Comment by beatles1** [comment]
Amazing, thank you so much for the super quick reply. That has worked great!
