### ISSUE TITLE
Date and Time not correct

### ISSUE THREAD

**Issue by kuhlivisj** [roflcoopter/viseron#55]
The date and time don't seem to be correct in the container. It seems to be the UTC time.
I have added /etc/localtime to the docker run command.

I think it is missing the tzdata package in the container. After installing it in the container the local date and time worked.

I have also added TZ=Europe/Amsterdam as variable to the docke run command but I am not sure if this is also necessary.

**Comment by roflcoopter** [comment]
Interesting, I do not experience this issue.

What does your docker run/docker compose look like?

**Comment by kuhlivisj** [comment]
This is the docker run command:

`docker run -d --name='Viseron' --net='br0' --ip='10.0.1.42' --privileged=true -e TZ="Europe/Berlin" -e HOST_OS="Unraid" -v '/mnt/user/Cameras/Viseron':'/recordings':'rw' -v '/mnt/user/appdata/Viseron':'/config':'rw' -v '/etc/localtime':'/etc/localtime':'ro' --device=/dev/dri:/dev/dri 'roflcoopter/viseron-vaapi:latest`

**Comment by roflcoopter** [comment]
Hmm strange. I will add in the tzdata package. Thanks for figuring it out!
