### ISSUE TITLE
DevContainer Tasks/Debugging Issues

### ISSUE THREAD

**Issue by tbarsen85** [roflcoopter/viseron#566]
I'm interested in helping out with the coding for this project, it has a lot of potential. I see the Dev Documentation is still a wip but I was able to setup the new Dev Container in VS Code per instructions here: https://github.com/roflcoopter/viseron/blob/dev/docs/docs/developers/development_environment/setup.mdx

I am running into issues building and debugging the Frontend. I have not made any code changes yet but I get the same outcome even if I do change something simple like the title of one of the webpages.

When doing the Task: "Frontend: Build" it errors out quickly with the output below

 *  Executing task: npm run build 
> frontend@0.1.0 build
> tsc && vite build

sh: 1: tsc: not found

 *  The terminal process "/bin/bash '-c', 'npm run build'" terminated with exit code: 127. 
 *  Press any key to close the terminal. 

When doing the Task: "Frontend: Start" it errors out quickly with the output below

 *  Executing task: npm run start 
> frontend@0.1.0 start
> vite --host

sh: 1: vite: not found

 *  The terminal process "/bin/bash '-c', 'npm run start'" terminated with exit code: 127. 
 *  Press any key to close the terminal. 

This may be related to above but also when under "Run and Debug" in VS Code. If I choose "Frontend Debug" it will launch the browser and load with url set to about:blank . This is also with "Viseron" running in "Run and Debug". I see in launch.json it should be loading url: http://localhost:5173 but when pointing to that it never loads and there is no Running Process under that port.

**Comment by roflcoopter** [comment]
Awesome that you want to help out!

Seems `npm install` did not run properly, does it work if you first `cd frontend` and then run `npm install`?

**Comment by roflcoopter** [comment]
Also you can find the developer docs here: https://dev--viseron.netlify.app/docs/developers
As you said they are a work in progress but there might be something useful for you there

**Comment by tbarsen85** [comment]
Thanks for the link. 

After doing the `cd frontend` and then `npm install` the errors are gone and the Tasks are working. I rebuilt the container a few times and could reproduce the same situation each time.

**Comment by roflcoopter** [comment]
Alright, and on your host? Thinking if its a permission issue between the host and the container
