### ISSUE TITLE
DevContainer - Testing Changes Issue

### ISSUE THREAD

**Issue by tbarsen85** [roflcoopter/viseron#568]
I'm sure once the Dev Documentation is up things will be a lot more clearer. As for now, in the DevContainer using the Tasks and Debugging options provided I am unable to fully test any changes done to the Frontend. 

I can make changes and build using Task "Frontend: Build" which result in seeing the changes when launching "Frontend: Start" but I am receiving http proxy errors shown below. I can only get so far as it is navigating me to the login page since it can't talk to the backend and is resulting with those proxy errors. I have also done "Run Viseron" but that just loads the frontend without any of my changes that I did and I'm not seeing any other location to edit the files. 

> 12:39:36 AM [vite] http proxy error at /api/v1/auth/login:
> Error: getaddrinfo ENOTFOUND undefined
>     at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:109:26) (x3)
> 12:39:43 AM [vite] http proxy error at /api/v1/auth/enabled:
> Error: getaddrinfo ENOTFOUND undefined
>     at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:109:26)
> 12:39:43 AM [vite] http proxy error at /api/v1/auth/token:
> Error: getaddrinfo ENOTFOUND undefined
>     at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:109:26)
> 12:40:00 AM [vite] http proxy error at /api/v1/auth/login:
> Error: getaddrinfo ENOTFOUND undefined
>     at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:109:26)

**Comment by roflcoopter** [comment]
You need to setup the proxy (so you can connect your local dev env with another running Viseron instance)
If you want to run Viseron inside the Dev Container and have it serve your changes you need to run `npm run build` and move the files to the correct location but it is easier to setup the proxy.

The proxy part is here: 

To fix it you need to create a `.env.development` file inside the `frontend` directory with these contents:
```
VITE_PROXY_HOST=<HOST>:<PORT>
```

Host and port should point to your running Viseron instance.
Will add this information to the docs right away.

Thanks a lot for bearing with me and reporting these issues!

**Comment by tbarsen85** [comment]
Awesome, it is working except one piece mentioned below. Also may I suggest having that `.env.local` file already created in the DevContainer and pointing to the localhost:8888 instance that runs when you run `Run Viseron` . Then you can state in the documentation that you can point the frontend else where by editing that file.


Getting the following error every few seconds in the console on all pages. Everything else works except the Configuration page never loads the configuration and stuck at "Loading Configuration". I set the proxy to an internal Viseron but also tested on an external instance of Viseron.

> Socket connection to 'ws://localhost:5173/websocket' failed: Error during WebSocket handshake: Unexpected response code: 403
> connect @ websockets.ts:58
> (anonymous) @ websockets.ts:159
> createSocket @ websockets.ts:157
> connect @ websockets.ts:210
