### ISSUE TITLE
MQTT Connection Errors Non-Obvious

### ISSUE THREAD

**Issue by sdwilsh** [roflcoopter/viseron#59]
I had a typo in my username, which resulted in the MQTT connection not working.  However, this wasn't apparently from the logs until I enabled `DEBUG`-level logging:
```
[2020-10-11 10:47:46] [lib.mqtt    ] [DEBUG   ] - MQTT connected with result code 5, message repeated 66 times
```

Looking at [the library's source code](https://github.com/eclipse/paho.mqtt.python/blob/2e69b8ebfbbc59981f5d9f0ae7974738f1df5b5a/src/paho/mqtt/client.py#L452) (I don't see any docs that explain this), it looks anything non-zero is an error.  It would be great to have an `ERROR`-level message that gives more context that the MQTT connection is not working.

**Comment by roflcoopter** [comment]
Yes any return code other than 0 should log an error, will fix!
