### ISSUE TITLE
Documentation is unavailable github and viseron.netlify.app

### ISSUE THREAD

**Issue by DrGusGus** [roflcoopter/viseron#602]
The dev branch of Viseron does not contain the path components-explorer and the online documentation does not seem to be available.

**Comment by roflcoopter** [comment]
Seems to work fine for me, the dev docs are located here: https://dev--viseron.netlify.app/components-explorer

And the components-explorer code is here:  https://github.com/roflcoopter/viseron/tree/dev/docs/src/pages/components-explorer

**Comment by DrGusGus** [comment]
My apologies, the issue is on my end.
