### ISSUE TITLE
Unable to play recordings on Chrome

### ISSUE THREAD

**Issue by ItsMeRitch** [roflcoopter/viseron#618]
When trying to reply any recordings from Chrome browser on Windows 10, I get the following error message:

![image](https://github.com/roflcoopter/viseron/assets/55960162/b07cb382-a380-4c7f-ac16-dd7301ecee5c)

Same occurs in Edge. 

Works perfectly on iOS Safari and Chrome 

Unable to find any log information regarding this which makes me think this could be client side rather than server but thought I'd ask

Thanks

**Comment by roflcoopter** [comment]
Interesting, what codec is your camera using?

**Comment by ItsMeRitch** [comment]
I’ve a total of 3 cameras, one mjpeg and two H264. NVR set to records to extension .MP4 thought if that could have anything to do with it?

**Comment by roflcoopter** [comment]
Mp4 should work fine. Is your chrome browser updated?

Could you check the media info of the file using either vlc or ffprobe?

**Comment by ItsMeRitch** [comment]
Ended up getting it sorted. Turns out that H264 was playing on windows all along but my browser(s) were acting up. Mjpeg doesn’t play though but that’s to be expected?

**Comment by roflcoopter** [comment]
No the MJPEG stream should work as well.
They work on both my iPhone and Chrome using the latest versions of both
