### ISSUE TITLE
schedule / active time for recordings - control via api/mqtt/http

### ISSUE THREAD

**Issue by freisei** [roflcoopter/viseron#620]
Hi!

is it possible to configure times when recordings should be active? For example tigger recording only at night-time.

Personally it would be enough if i can switch some "recoding-active" value like sensor.camera_1_operation_state via http/mqtt or similar. By the way would such a api for example enable me to use my cameras internal motion detection to trigger recordings.

Nice Greets!

**Comment by roflcoopter** [comment]
This can sort of be accomplished by using the [MQTT Toggle Topic](https://viseron.netlify.app/components-explorer/components/mqtt#toggle-topics) to turn the camera on/off.

The downside of this is that Viseron will stop reading from the camera completely, meaning everything else also stops running (object detection, face recognition, MJPEG streams etc)
I have plans to make it possible to pause recordings, but i need to do an overhaul of the API first so it might take me some time

**Comment by freisei** [comment]
Thank you very much. I dont why i have overseen the mqtt-component :)
