### ISSUE TITLE
recordings and config root ownership

### ISSUE THREAD

**Issue by ceewanna** [roflcoopter/viseron#630]
I observe that both config and recording files/folders are taken ownership by root once, viseron docker runs. Even I include my user to docker group and run the container, the config files/folder ownership turns to root.

**Comment by roflcoopter** [comment]
That is correct, the recordings/config folders permission is set to match the running user.
If you want to change the running user, you can do so by following these instructions: https://viseron.netlify.app/docs/documentation/installation#user-and-group-identifiers

**Comment by ceewanna** [comment]
From my experience so far, I haven't specified -e options but run one in systemd service (root) and the other on command line by my account user (for testing parameters). The result was both approaches turned the config folder and files into root. It didn't quite seem to follow the running user.

From your advise, I explicitly specified -e option and it turned out fine now.
Thanks.
