### ISSUE TITLE
Recordings being delete

### ISSUE THREAD

**Issue by ItsMeRitch** [roflcoopter/viseron#664]
Hi folks,

I'm having an issue where days of recordings keep disappearing, for instance, I checked last night that I had recordings from 27-09-2023 and now that whole folder is gone. 

Trying to track down to see if its Nextcloud that is the issue or is there a settings where Viseron overwrites old recordings? 

Thanks

**Comment by roflcoopter** [comment]
Viseron deletes recordings after 7 days by default.
You can control for how long you want to store them using the `retain` config option under `recorder`

**Comment by ItsMeRitch** [comment]
ahhh that explains it, was pulling my hair out at this haha. thank you!

**Comment by ItsMeRitch** [comment]
Forgot to add, would there maybe be room for this to be included into the NVR component in the docs?

**Comment by ItsMeRitch** [comment]
nvm, it is, im just stupid, please feel free to delete this issue haha

**Comment by AdnanHussainTurki** [comment]
Guys, do we have any documentation to where to add that `retain` key-value pair?

**Comment by roflcoopter** [comment]
You can find it in the component docs for FFmpeg/GStreamer under the `recorder` settings

https://viseron.netlify.app/components-explorer/components/ffmpeg
