### ISSUE TITLE
Multiple Coral TPUs

### ISSUE THREAD

**Issue by bailboy91** [roflcoopter/viseron#667]
Does viseron utilize multiple coral tpus?  I have 2 pcie tpus passed through to the container but don't have a way to measure utilization of them.  These are 2 separate tpus not the double chipped one btw.  

I have verified on startup my viseron container does see both TPUs.

**Comment by roflcoopter** [comment]
No Viseron only supports one coral sadly.
Would love to support more but don't have the time right now sadly
