### ISSUE TITLE
CodeProject AI docs

### ISSUE THREAD

**Issue by mckochan** [roflcoopter/viseron#670]
Thanks for adding CodeProject AI!
I'm not seeing CodeProject AI in the docs or component list. I do see where you edited some of the backend doc files, but it is not showing up for me at https://viseron.netlify.app/

**Comment by roflcoopter** [comment]
Thanks for letting me know, will look into it right away!

**Comment by roflcoopter** [comment]
Should be fixed now! The deploy was cancelled for some reason.
You can find it here: https://viseron.netlify.app/components-explorer/components/codeprojectai

If you still dont see it, try clearing your cache
