### ISSUE TITLE
Jetson nano viseron: No module named 'gi'

### ISSUE THREAD

**Issue by RyanPostema** [roflcoopter/viseron#671]
Hi, hope you are doing well! 

Recently i tried running the jetson nano viseron image, and as described is the documentation, tried configuring the gstreamer component. 

During startup i get the following error: 

`Failed to load component gstreamer: No module named 'gi'`

subsequent components also fail, as this is the only camera. 

- container is running in privileged mode
- container is running on a jetson nano 4gb 

All this was tested on **2.3.0** jetson nano viseron (or **latest**.) 
I already tried finding a work around, but had no success. the sys.path python path (python3.8.5) did not contain any gi, linking gi to this path did not work, because of a circular import error. 

**2.2.0** seems to at least not give the same error. 

Please let me know if i can do anything else.

**Comment by roflcoopter** [comment]
Seems to be a problem because the container installs python 3.8, but the installed `python3-gi` encounters a conflict with python 3.6 for some reason.

Will see if i can install `gi` from `pip` instead of `apt`

**Comment by roflcoopter** [comment]
I think i fixed the issue, builds are in progress currently, will let you know when its ready to test

**Comment by RyanPostema** [comment]
hi @roflcoopter! 

What a quick response! I am currently pulling the new image (**2.3.1**) and will let you know the result.

**Comment by roflcoopter** [comment]
Great, thanks for verifying!
