### ISSUE TITLE
How to turn off recording。

### ISSUE THREAD

**Issue by LZZJ** [roflcoopter/viseron#698]
Here is my configuration file.

########################################################################
ffmpeg:
  camera:
    thoughtallroomtest1:  # This value has to be unique across all cameras
      name: thoughtall
      host: 119.180.24.78 #<ip address or hostname of camera>
      port: 554 #<port the camera listens on>
      path: /rtp/37069900001180001011_37069900001180001011 #.live.flv #<URL path to the stream>
      username: #<if auth is enabled>
      password: #<if auth is enabled>
      stream_format: rtsp
      protocol: rtsp
      # codec: h264_cuvid
      # width: 1920
      # height: 1080
      fps: 15
      mjpeg_streams:
        static:
          # rotate: 180
          # width: 100
          # height: 100
          draw_objects: true
          draw_zones: true
          draw_object_mask: true
          draw_motion: true

mog2:
  motion_detector:
    cameras:
      thoughtallroomtest1:  
        fps: 1

nvr:
  #传奥
  thoughtallroomtest1:  # Run NVR for camera_1

fastdeployserver:
  host: 119.180.24.78
  port: 8161
  model_name: ppdet
  model_version: "1"
  label_path: "viseron/components/fastdeployserver/labels"
  object_detector:
    cameras:
      thoughtallroomtest1:  # Attach detector to the configured camera_1 above
        fps: 1
        scan_on_motion_only: true  # Scan for objects even when there is no motion
        labels:
          - label: person
            confidence: 0.65
            #trigger_recorder: true
###################################################################

After running the visieron, it will generate recordings in the segments directory under the root directory.It will take up a lot of my storage space. May I ask how to turn it off?

**Comment by roflcoopter** [comment]
You need to set `trigger_recorder: false`, since the default is `true` if not specified
