### ISSUE TITLE
Incorrect FPS reported?

### ISSUE THREAD

**Issue by cwallace** [roflcoopter/viseron#7]
I'm not sure if this is an issue with the detection of my camera or if this is reporting bitrate instead of FPS?

[2020-09-04 10:42:08] [lib.camera.front_yard ] [INFO ] - Resolution: 640x480 @ 180000 FPS

**Comment by roflcoopter** [comment]
That looks interesting to say the least!
OpenCV is used to get the FPS of the stream, which isnt fool-proof. Some cameras seem to not play nice.

To solve this you can manually specify FPS in your config
```yaml
fps: 6  #input your cameras FPS here
```

**Comment by roflcoopter** [comment]
Closing as this hould be resolved. Feel free to reopen if you still are having issues
