### ISSUE TITLE
file permission setting for recording folders and files

### ISSUE THREAD

**Issue by ceewanna** [roflcoopter/viseron#702]
There is -e PUID=1000  -e PGID=1000 for setting user and group id. However, what would be the proper approach for handling file permission for recording folders and files, something like umask. Should we just set it via chmod command? Would it be overwritten when docker run is executed?

**Comment by ceewanna** [comment]
I guess that is not necessary now. I could get things done via acl. Sorry for asking such nonsense.

**Comment by roflcoopter** [comment]
The docker container changes the permission of the folders to be owned by the running in PUID and group in PGID, umask is not being used
