### ISSUE TITLE
How to ignore audio on event recording

### ISSUE THREAD

**Issue by csuther28** [roflcoopter/viseron#744]
Hi, 

My camera setup as follows:
'''
ffmpeg:
  camera:
    camera_1:  # This value has to be unique across all cameras
      name: Driveway
      host: 192.168.0.103
      port: 554
      path: /h264Preview_01_main
      protocol: rtsp
      width: 2560
      height: 1920
      fps: 15
      audio_codec: null  #aac
      username: !secret ovif_user
      password: !secret ovif_pwd
      recorder:
        filename_pattern: '%H%M%S'
'''

My Reolink has built-in microphone that works really well. It's great to have the audio when doing playback.
However, from some of the footage recorded, it seems the recording has been triggered by audio.
So I then tried to disable the camera audio as per above with the value 'null', but the playback still contains audio, which again I have no issue with.
But I've just checked and for sure I have some recordings which seems to have been triggered by audio, i.e. loud noises triggering the recording...how to disable?

**Comment by roflcoopter** [comment]
Recordings do not trigger on audio, no processing of audio exists in Viseron.
So there must be something else, probably motion that triggers it.

The logs should tell you more about what triggered the recording
