### ISSUE TITLE
Error validating config for domain camera and component gstreamer

### ISSUE THREAD

**Issue by cdmichaelb** [roflcoopter/viseron#747]
`ffmpeg_recoverable_errors` will not help in this regard unfortunately.

Some cameras doesnt report their FPS correctly, (as you can see from the log FFprobe found Width, Height but no FPS, so you could just add `fps: CAMERA_FPS_HERE` to your camera config.

If you specify `width`, `height`, `fps`, `codec` and `audio_codec` in the config, then the call to FFprobe to get stream information will be skipped entirely and startup will be much faster, but there is a bug that causes Viseron to crash if you set `audio_codec` which i am going to push a fix for in a few minutes.

_Originally posted by @roflcoopter in https://github.com/roflcoopter/viseron/discussions/207#discussioncomment-849628_

I get the same exact error. I tried specifying an FPS. FPS: 25. And get this error now:
Error validating config for domain camera and component gstreamer: extra keys not allowed @ data['camera_1']['FPS']. Got None.

Same problem whether I use ffmpeg or gstreamer.

**Comment by roflcoopter** [comment]
`fps` has to be in lower-case, does that help?

**Comment by cdmichaelb** [comment]
It worked! Thanks, I can't believe I missed that. Spent hours trying to figure it out.

**Comment by roflcoopter** [comment]
Great!
