### ISSUE TITLE
Error upon startup

### ISSUE THREAD

**Issue by dcgrove** [roflcoopter/viseron#75]
Hello, I am getting this error on startup. My config is below. This is installed on an rpi 3B+

```
[2020-11-04 18:19:06] [lib.camera.driveway     ] [ERROR   ] - Error starting decoder pipe! mmal: mmal_vc_port_info_set: failed to set port info (2:0): EINVAL
mmal: mmal_vc_port_set_format: mmal_vc_port_info_set failed 0x206a8b0 (EINVAL)
mmal: mmal_port_disable: port vc.ril.video_decode:in:0(H264)(0x206a8b0) is not enabled
mmal: mmal_port_disable: port vc.ril.video_decode:out:0(0x206abd0) is not enabled
mmal: mmal_port_disable: port vc.ril.video_decode:ctr:0(0x2065920) is not enabled
 Retrying in 5 seconds
```

`# See the README for the full list of configuration

cameras:
  - name: Driveway
    mqtt_name: viseron_driveway
    host: 192.168.1.19
    port: 554
    username: XXXXXX
    password: XXXXXXX
    path: /h264Preview_01_main
    width: 2560
    height: 1920
    fps: 30
    motion_detection:
      interval: 1
      trigger_detector: false
    object_detection:
      interval: 1
      labels:
        - label: person
          confidence: 0.9

# MQTT is optional
mqtt:
  broker: 192.168.1.76
  port: 1883
  username: homeassistant
  password: XXXXXXXXX
`

**Comment by roflcoopter** [comment]
Can you show me your docker run/docker compose?

**Comment by dcgrove** [comment]
Hello, thanks for the help, this is what I used to run the container.

**Comment by roflcoopter** [comment]
Have you increased the allocated GPU memory as indicated in the README?
Included the snippet below (Its under the Raspberry Pi 3b+ section in Getting Started)
*To do this edit /boot/config.txt and set gpu_mem=256 and then reboot.*

**Comment by dcgrove** [comment]
I changed the camera to the substream and increased the GPU memory and all is working now.  Thanks!
