### ISSUE TITLE
Hardware acceleration

### ISSUE THREAD

**Issue by MPueschel** [roflcoopter/viseron#771]
Hello,

I would like to use hardware acceleration for Darknet. Unfortunately, OpenCV or OpenCL cannot find a suitable hardware/GPU. However, the hardware acceleration works with ffmpeg without any problems. Can you give me a tip on how to get OpenCV/OpenCL to work on the GPU?

As an addition: I have tried it on two machines without success - i5-9500T and G4560T.

Thanks.

**Comment by roflcoopter** [comment]
Can you show me your docker run command? Or docker-compose if you are using that

**Comment by MPueschel** [comment]
Hi roflcoopter,
my docker-compose.yml looks like this:
_services:
  viseron:
    image: roflcoopter/viseron:latest
    container_name: viseron
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    volumes:
      - /home/ubuntu/Docker/Viseron/recordings:/recordings
      - /home/ubuntu/Docker/Viseron/config:/config
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 8888:8888
    devices:
      - /dev/dri:dev/dri_

**Comment by roflcoopter** [comment]
Looks good!

Might be driver compatibility issues, the latest beta, docker tag 3.0.0b7, uses Ubuntu 22.04 as the base image which includes newer drivers. Could you try that?

**Comment by MPueschel** [comment]
Thanks, this fixed my issue.

**Comment by roflcoopter** [comment]
Great!
