### ISSUE TITLE
Suspected Timezone Issue...

### ISSUE THREAD

**Issue by sgoldtho** [roflcoopter/viseron#781]
Recordings appear to have the correct time but are being save according to UTC rather than local timezone AEST.

For example a recording that happened today 12/07/2024 @ 9:29:09 is being displayed under 2024/07/11 in the web interface.

Using Viseron 3.0.0b8

**Comment by roflcoopter** [comment]
Yes that is a known issue! Will be fixed in the next beta

**Comment by sgoldtho** [comment]
Thanks

**Comment by roflcoopter** [comment]
Sorry for the delay on this one.
This should be fixed in `dev` now.

Would you mind testing it? Unit tests are working fine but I am only one hour off UTC so it is hard for me to verify end to end

**Comment by sgoldtho** [comment]
First test was this morning just past midnight so might be a bit close to be useful..

Detected an event at 00:09:48 on the 02/11/2024 which showed in Viseron under 01/11/2024.

Noticed a couple of other things:
1) When selecting the ‘View Recordings’ icon on a day the error message ‘Error loading recordings Request failed with status code 500’ is returned.
Not sure what that is about as the path exists but there are no files in the directory

2) When the GUI is in light mode it appears that the font is white with a white background, so when hovering over an icon the text box appears blank.

**Comment by roflcoopter** [comment]
Thanks for testing so quickly!
Yes I found some more issues, can hopefully have them fixed later today.

Will take a look on the font color as well

**Comment by roflcoopter** [comment]
Now these issues should be solved, both the recordings and the tooltip font color.

Please run some tests when you get the chance.
I would appreciate if you could have a look on the events/timeline page as well to see if you notice anything strange there regarding dates.

I have done by best to make sure all cases are covered but it gets very complex when you mix and match different timezones in the client vs the server!

**Comment by sgoldtho** [comment]
Test results:

Tooltip font colour: No issues detected (fixed).
Recordings grouped into correct date: No issues detected (fixed).
Recordings playback:  No issues detected (fixed).

Nothing strange detected with dates using the Events/Timeline page.

Looks good...

**Comment by roflcoopter** [comment]
Great to hear! Closing this issue then. Please open a new one if you experience any other issues
