### ISSUE TITLE
Stop recording during an event

### ISSUE THREAD

**Issue by ogmkp** [roflcoopter/viseron#799]
Hi and thank you for this great project !

Is it possible to set ffmpeg to stop recording during an event? For example, if a person is detected, I'd like ffmpeg to record for 30 seconds, which produces a file and then start a new recording file for 30 sec as long as the event is still present ?

Thanks !

**Comment by roflcoopter** [comment]
In the 3.0 beta the config option `max_recording_time` is available which does exactly what you need!

You put it under the `recorder` section of your camera configuration

**Comment by ogmkp** [comment]
Great ! I have another demand: Will it be possible to have a smtp component with ability to send immediatly an e-mail on starting event with screenshot and after recording is done to send an e-mail with the video ? 

Thanks !

**Comment by roflcoopter** [comment]
In the future for sure, but right now i am busy with the 3.0 release and cant give a timeline on when i can implement smtp.
