### ISSUE TITLE
[FR] - Unraid (Docker) community App

### ISSUE THREAD

**Issue by jaburges** [roflcoopter/viseron#8]
This one was on the reddit thread.

Unraid is an OS that provides a GUI for a PC behaving as a NAS, but includes VMs and dockers.

There is a community app store (similar to the Synology NAS docker repository) where you can download an 'app' (docker) and specify variables (volumes, ports, env etc) inside the GUI. 

App store here: [](https://forums.unraid.net/topic/38582-plug-in-community-applications/)
To create a template info here: [](https://forums.unraid.net/topic/57181-docker-faq/#comment-566084)

Benefit to this is it checks for updates and the docker can be updated via the GUI easily.
HTH

**Comment by JoeGandy** [comment]
If you wanted to go down this route @roflcoopter I've setup the template for you, as i know you're not an unraid user:

It wouldnt let me upload the xml directly, so its zipped here:
[Viseron.zip](https://github.com/roflcoopter/viseron/files/5184000/Viseron.zip)

Instructions on what to do on are on here:
https://forums.unraid.net/topic/57181-docker-faq/?do=findComment&comment=566084

Specifically this is what to do next (I don't want to do it for you as its your project! so you may want your name on it!)
Publishing to CA

- Create a GitHub repository and upload the XML(s).  Use a separate repository for your xml files.  (Keep it separate from the docker associated files if you've built your own container).  If you have multiple templates, put them all into the same repository.   NOTE:  The XML files must be within the "master" branch of the repository
- Drop myself (squid)  a PM asking for it to be published with a link to the github repo.
- I'm going to  insist you create a <Support> thread.  Just create it anywhere (as you won't be able to create in the docker Containers) and a moderator will move it.  Update the XML with the support link.  I will also insist on Categories being set.  
- I do a quick check on the xml(s) and then add it to CA.  If there are no major problems, within 2 hours all users of CA will have access to it under normal circumstances.
- Time permitting after its available to all users of CA, I will update the Repositories thread

**Comment by roflcoopter** [comment]
This is great! Thanks for all the details.
I'll go through it tomorrow morning

**Comment by roflcoopter** [comment]
I have taken the first two steps and created a repository + messaged Squid on the unRAID forum. Still waiting for a reply

**Comment by roflcoopter** [comment]
I think it might be up now, Squid just told me it was. Can any of you guys check?
I will post a support thread there once my account gets post access

**Comment by jaburges** [comment]
yep its up :)

**Comment by jaburges** [comment]
just tested with viseron-cuda too (added the runtime=nvidia ENV vaiable) 

However i'm getting 
```
[2020-09-10 18:05:49] [lib.camera.front ] [ERROR ] - Error starting decoder pipe! [h264_cuvid @ 0x55fbfd4fda40] Cannot load libnvcuvid.so.1

[h264_cuvid @ 0x55fbfd4fda40] Failed loading nvcuvid.

Error while opening decoder for input stream #0:0 : Operation not permitted
```

**Comment by roflcoopter** [comment]
> just tested with viseron-cuda too (added the runtime=nvidia ENV vaiable)
> 
> However i'm getting
> 
> ```
> [2020-09-10 18:05:49] [lib.camera.front ] [ERROR ] - Error starting decoder pipe! [h264_cuvid @ 0x55fbfd4fda40] Cannot load libnvcuvid.so.1
> 
> [h264_cuvid @ 0x55fbfd4fda40] Failed loading nvcuvid.
> 
> Error while opening decoder for input stream #0:0 : Operation not permitted
> ```

I am not an expert on unRAID but could you take a look at [this](https://forums.unraid.net/topic/76878-support-josh5-unmanic-library-optimiser/) and follow the steps under **Nvidia GPU hardware encoding**?

**Comment by roflcoopter** [comment]
Closing this as Viseron now is up on unRAID CA
