### ISSUE TITLE
question about docker images

### ISSUE THREAD

**Issue by Ranger21** [roflcoopter/viseron#816]
I've found out that using latest tag on docker image doesn't update app 
roflcoopter/viseron:latest

On docker hub  i can't see avalaible image with latest tag

what's the proper way of updating docker image and which version is considered latest kinda "stable"?

**Comment by roflcoopter** [comment]
`latest` tag corresponds to the latest stable release.
There has not been one in quite some time, but there is a beta going on right now for v3, which is currently `3.0.0b10`

**Comment by Ranger21** [comment]
Ok, thank you, I'll try newer version
