### ISSUE TITLE
ffprobe ignores the `rtsp_transport` setting and fails to probe the camera

### ISSUE THREAD

**Issue by jin-eld** [roflcoopter/viseron#830]
Hi,

I am setting up a camera surveillance system and I am trying out Viseron for the first time. So far I am not able to add my camera and after longer fiddling I think I found out what the issue may be.

Viseron uses `ffprobe` to get some info about the stream coming from the camera, this kept failing:
```
[2024-11-08 21:19:02] [ERROR   ] [viseron.components.ffmpeg.stream.camera_1] - Retrying None in 2.0 seconds as it raised FFprobeTimeout: FFprobe command timed out after 15s.
```

Since I was able to play the rtsp URL with `vlc` I figured I'd also try `ffprobe` on my notebook and it hangs when probing the stream. Turned out, that for some reason UDP does not seem to work for me, so `ffprobe` requires the `-rtsp_transport tcp` parameter, then it returns the stream information right away.

I checked Viseron documentation and there is a config option called `rtsp_transport` which according to the docs is anyway set to `tcp` by default, I still did set it just to be sure, but it seems that this setting is not being propagated to the `ffprobe` call:
```
[2024-11-08 21:18:47] [DEBUG   ] [viseron.components.ffmpeg.stream.camera_1] - FFprobe command: ffprobe -hide_banner -loglevel error -print_format json -show_error -show_entries stream=codec_type,codec_name,width,height,avg_frame_rate rtsp://*****:*****@xxx.xxx.xxx.xxx:554/stream=0
```

I still need to investigate why UDP is not working on my camera, but currently this is quite a blocker for me, because I can't tell Viseron to use tcp when probing and thus it just keeps spinning, trying to register the camera :(

**Comment by roflcoopter** [comment]
Sorry you are having issues!

You are correct, ffprobe does not look at the RTSP transport.
Over the years i have had many users with the same issue, FFprobe timing out.
This might be the solution to that! 

Made some quick changes, builds should be done in a few minutes.

**Comment by roflcoopter** [comment]
You can follow the build progress here: https://dev.azure.com/jespernilsson93/Viseron%20Pipelines/_build?definitionId=8&_a=summary

When it is done you can try it out by pulling the `dev` Docker tag

**Comment by jin-eld** [comment]
@roflcoopter wow, that was fast, thank you! The `dev` build worked fine, I can confirm that your fix solved the issue for me.

**Comment by roflcoopter** [comment]
Great! Yeah it was easy since you figured out the problem already so thanks for that
