### ISSUE TITLE
Problems building viseron from Dev Container in vs code

### ISSUE THREAD

**Issue by tantonj** [roflcoopter/viseron#841]
I am attempting to follow the instructions here https://viseron.netlify.app/docs/developers/development_environment/setup

I've run into some problems, preventing me from building the application and wondering if anyone has run into these before. I should note that this is the first time I've worked with dev containers in vs code and am fairly new to docker in general.

When the container first loads I get the following error:
![viseronerr1](https://github.com/user-attachments/assets/be32021b-3bb3-4271-a00b-b82bbbcc9acb)
It appears to be some kind of issue with the container's access to docker, which I do not understand.

If I ht the edit devcontainer.json option, I see nothing wrong with the json. At first i thought the python path was set wrong, but I soon realised that path is relative to the container and not my system. If I attempt to build the project with the Viseron launch option I get the following error:
![viseronerr2](https://github.com/user-attachments/assets/acc8f421-141f-43f0-94a4-92d6590844fd)
The error being what is shown in the terminal, the vscode popup only appears if I click on the viseron/__init__.py file. This is strange as I use pylance on my local repos with no issues. My system does have $JAVA_HOME, but clearly this is trying to reference javahome relative to the container. If I attempt the Automatically download java option it downloads but immediately pops up again, as if it failed. If I attempt to specify manually I only have access to the container's directories and see no java home location. If I cancel, you will notice the following in __init__.py
 
![viseronerr3](https://github.com/user-attachments/assets/e6b93c55-d6fb-486e-b21b-fde2f5c2ed08)

these libraries can't be resolved by pylance. I'm not sure if it is safe to ignore the first error, but I figure if I can solve the java_home issue, I may be able to build the application.

Any assistance with this would be greatly appreciated

**UPDATE**

This was a fairly silly problem. With it being my first experience with dev containers I assumed that the setup would install any required packages. I needed to go through and do pip install on all missing packages in the dev containers terminal. However, I am struggling with installing opencv-python. It first gave the error  No module named 'distutils'. Googling this led me to the solution of installing setuptools. However, now when I install I get AttributeError: module 'pkgutil' has no attribute 'ImpImporter'. Did you mean: 'zipimporter'? I've attempted the solutions suggested when googling the problem, other than down grading to python 3.11. It appears the package is out of date.

**Comment by roflcoopter** [comment]
Sorry thats an error on my part.
Before you start the Devcontainer you need to create an empty `config` folder in the repo.

Will make sure to fix that asap. One other user has reported that earlier but i must have forgotten to add it.

You should not have to pip install anything manually. I suspect you are not actually running inside the Devcontainer since the bindmount failed due to the config folder missing?

**Comment by roflcoopter** [comment]
The `config` folder is now commited to the repo.

Please let me know if you still have issues with the python deps.

**Comment by tantonj** [comment]
I've found this post here:
https://stackoverflow.com/questions/65306511/cannot-connect-to-workspacemount-at-container-launch-from-vscode
When I go to edit the devcontainer.json file, there is no workspaceMount or folder specified.
My best guess is that whatever is the owner of the devcontainer does not have docker permissions.

**Comment by roflcoopter** [comment]
Hmm it works fine here.

Can you clone the repo manually, then open the folder in VSCode and press F1 > Rebuild container  without cache?

**Comment by tantonj** [comment]
Excellent! That worked. Thanks Jesper!

For anyone looking at this post in the future. I cloned roflcoopters' repo (though I'm sure my fork would have worked too). Then I did as suggested above, rebuilt the container in vscode after opening up the folder. This worked, but before building I needed to replace my config.yaml in the config folder with what I had on my docker-compose build. Then I needed to manually copy in my secrets.yaml (as I was referencing secrets in my config). Finally for my events to properly load I needed to manually add in my face_recognition/faces/<person names> folder structure. Once this was done I could build the viseron launch configuration and the viseron server was running from code exactly as it did from docker-compose.

Now for the fun part adding some new endpoints!!!!!!

**Comment by roflcoopter** [comment]
Great!

I did some more tests and also got the bind mount error even tho the config folder was there. Seems sporadic, guess it's a cache issue.

Anyway it seems the bind mount is not needed since the setup script creates the folder if it is missing so I'll remove it
