### ISSUE TITLE
Events - Select Date

### ISSUE THREAD

**Issue by Tlong21** [roflcoopter/viseron#851]
## Issue Summary
In the **Events** section, under **Select Date**, I cannot choose any date other than "Today" or dates with clips.  

I only use Viseron for the new **24/7 recording feature** and do not record clips. It would be great to confirm whether this behavior is intentional or if it’s a bug.

---

## Steps to Reproduce
1. Go to **Events** in the Viseron UI.
2. Click on **Select Date**.
3. Attempt to select a date with no clips or events.

### Expected Behavior
I should be able to select any date (even if no clips exist) to review the continuous 24/7 recordings.

### Actual Behavior
I can only select "Today" or dates with clips/events.

Let me know if you need anything else!
Love the project and I appreciate you help.

---

## Screenshot
![Screenshot 2024-12-09 115832](https://github.com/user-attachments/assets/2447ba6c-f9e7-4c24-87d0-6eb93f1fcfb4)

---

## Configuration - V3.0.0b12

```yaml
ffmpeg:
  camera:
    camera_1:  
      name: Front Door
      host: ****
      port: ****
      path: /h264Preview_01_main
      username: ****
      password: ****
    camera_2:  
      name: Back Yard
      host: ****
      port: ****
      path: /h264Preview_01_main
      username: ****
      password: ****

nvr:
  camera_1:  # Run NVR for camera_1
  camera_2:  # Run NVR for camera_2

storage:
  recorder:
    tiers:
      - path: /recordings
        check_interval:
          days: 7
        continuous: 
          max_age:
            days: 14

**Comment by roflcoopter** [comment]
That is working as intended, but i see now that its an oversight from my side.

You should of course be able to view different dates even tho there are no events.
Would be better to allow for selection of dates that have corresponding video files instead.
That way you would easily see how for back you can go.

Wil fix for the next beta!

**Comment by Tlong21** [comment]
I look forward to the future updates! 
Thank you for confirming.

**Comment by roflcoopter** [comment]
Latest `dev` tag should include a fix for this.

Builds will be done shortly. You can follow the progress here: https://dev.azure.com/jespernilsson93/Viseron%20Pipelines/_build/results?buildId=744&view=results
